Create API-012-content-type.md
dapr/dapr pull request #2053
Opened 2020-09-16 02:41 UTC by artursouza

# Description

ADR for content-type.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/2026

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [X] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2020-09-16 05:10 UTC, youngbupark requested changes
Please add this to the list of ADRs - https://github.com/dapr/dapr/blob/master/docs/decision_records/decision_records.md

2020-09-16 05:10 UTC, youngbupark commented on docs/decision_records/api/API-012-content-type.md
> +Rejected
Status is the status of this ADR. So, it is `Accepted` status.

2020-09-16 18:10 UTC, mukundansundar commented on docs/decision_records/api/API-012-content-type.md
> +
Can you link to the discussion issue here?

2020-09-18 09:02 UTC, youngbupark approved these changes

2020-09-18 19:17 UTC, merged