grpc middleware refactoring
dapr/dapr pull request #2056
Opened 2020-09-16 20:04 UTC by Haishi2016

Refactoring gRPC middleware

2020-09-16 20:41 UTC, tcnghia requested changes
Please add some unit tests?

2020-09-16 20:41 UTC, tcnghia commented on pkg/middleware/grpc/grpc_pipeline.go
> +}
`spec` isn't used. Is this intentional? If yes, can you replace `spec` by `_` to indicate so?

2020-09-16 20:41 UTC, tcnghia commented on pkg/middleware/grpc/grpc_pipeline.go
> +	ret := make([]grpc_go.UnaryServerInterceptor, 0)
Since length(ret) == length(p), can we just preallocate this with len(p.Interceptors) to avoid unnecessary resize?

2020-09-16 20:41 UTC, tcnghia commented on pkg/middleware/grpc/grpc_pipeline.go
> +	for i := len(p.Interceptors) - 1; i >= 0; i-- {
How important is the reverse ordering? If it is important, can you please add some comments to make sure others don't accidentally mess this up?

2020-09-16 20:41 UTC, tcnghia commented on pkg/middleware/grpc/grpc_pipeline.go
> +	for i := len(p.Interceptors) - 1; i >= 0; i-- {
Why not a `for i, interceptor := range p` loop?

2020-09-16 20:41 UTC, tcnghia commented on pkg/middleware/grpc/grpc_pipeline.go
> +	for i := len(p.Interceptors) - 1; i >= 0; i-- {
also, please add a test to confirm this ordering? thanks

2020-09-16 20:41 UTC, tcnghia commented on pkg/runtime/runtime.go
> +func (a *DaprRuntime) buildGRPCPipeline() (dapr_grpc_middleware.Pipeline, error) {
```suggestion

func (a *DaprRuntime) buildGRPCPipeline() (dapr_grpc_middleware.Pipeline, error) {
```

2020-09-16 20:41 UTC, tcnghia commented on pkg/runtime/runtime.go
> +			middlewareSpec := a.globalConfig.Spec.GRPCPipelineSpec.Handlers[i]
```suggestion
		for i, middlewareSpec := range a.globalConfig.Spec.GRPCPipelineSpec.Handlers {
```

2020-09-16 20:41 UTC, tcnghia commented on cmd/daprd/main.go
> +	//gRPC Middleware
Do we need this comment?

2020-09-16 20:41 UTC, tcnghia commented on pkg/middleware/grpc/grpc_pipeline.go
> +type Middleware func() grpc_go.UnaryServerInterceptor
Please add a doc comment?

2020-09-16 20:41 UTC, tcnghia commented on pkg/runtime/runtime.go
> +	var interceptors []dapr_grpc_middleware.Middleware
Seems len(interceptors) == len(a.globalConfig.Spec.GRPCPipelineSpec.Handlers), so may be we can preallocate here.

2020-09-16 20:41 UTC, tcnghia commented on pkg/runtime/runtime.go
> +			interceptors = append(interceptors, interceptor)
```suggestion
			interceptors[i] = interceptor
```

2020-10-02 16:20 UTC, closed without merging

2020-10-02 16:21 UTC, yaron2 commented
@tcnghia can you add a reason why this was closed?

2020-10-02 16:23 UTC, tcnghia commented
Yes @Haishi2016 is no longer working on this PR so closing it