improve log for debug in case of error
dapr/dapr pull request #2111
Opened 2020-09-25 12:59 UTC by skyao

# Description

Improve log for debug in case of error: don't eat it, at least write the error into log.

## Issue reference

#2109 

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2020-09-27 05:45 UTC, skyao commented
Hi, any feedback?

2020-09-28 16:01 UTC, yaron2 requested changes

2020-09-28 16:01 UTC, yaron2 commented on pkg/injector/pod_patch.go
> +		log.Errorf("Fail to load dapr configuration from k8s, use default value %t for mTLSEnabled: %s", defaultMtlsEnabled, err)
nit: `failed to load`

2020-09-28 16:01 UTC, yaron2 commented on pkg/injector/pod_patch.go
> +	log.Infof("Dapr system configuration is not found, use default value %t for mTLSEnabled", defaultMtlsEnabled)
Can you include the name of the configuration here?

2020-09-29 04:10 UTC, yaron2 approved these changes
lgtm

2020-09-29 04:11 UTC, yaron2 commented
/ok-to-test

2020-09-29 04:54 UTC, merged