Upgrade golangci-lint to v1.31.0
dapr/dapr pull request #2175
Opened 2020-10-01 21:51 UTC by bvwells

# Description

Upgrade golangci-lint to v1.31.0

## Issue reference

This will close #1951 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2020-10-01 21:52 UTC, bvwells commented
Work in progress.... Need to push further changes to fix other linting issues.

2020-10-02 19:39 UTC, bvwells commented
Should pass golangci-lint now...

2020-10-03 00:01 UTC, tcnghia requested changes
Thanks a lot for making this change

2020-10-03 00:01 UTC, tcnghia commented on pkg/grpc/api_test.go
> +	conn, err := grpc.Dial(fmt.Sprintf("localhost:%d", port), opts...)
```suggestion
	conn, err := grpc.Dial(fmt.Sprintf("localhost:%d", port), grpc.WithInsecure())
```

2020-10-03 00:10 UTC, tcnghia commented on .golangci.yml
> +    - gofumpt
Nevermind, I saw https://github.com/dapr/dapr/issues/1951#issuecomment-702924258 now .

2020-10-03 05:41 UTC, tcnghia commented
@bvwells I created a PR to have the linter annotated the PR directly https://github.com/dapr/dapr/pull/2186. Feel free to incorporate into this PR, or we can check it / rebase independently. Thanks

2020-10-03 06:51 UTC, bvwells commented on pkg/grpc/api_test.go
> +	conn, err := grpc.Dial(fmt.Sprintf("localhost:%d", port), opts...)
Bit outside the fix, but sure, updated.

2020-10-03 06:55 UTC, bvwells commented on pkg/actors/actors.go
> +					r := reminders[i]
Added comment on all instances of this.

2020-10-03 07:05 UTC, tcnghia approved these changes

2020-10-03 16:00 UTC, youngbupark approved these changes
LGTM. Thanks for your contribution!

2020-10-03 16:01 UTC, merged

2020-10-03 16:59 UTC, bvwells commented
Thanks all for the review and merge!