[WIP} Add performance tests for grpc service invocation
dapr/dapr pull request #2321
Opened 2020-10-24 09:07 UTC by wmeints

# Description

A new performance test for GRPC service invocation. This follows the same pattern as the performance test for HTTP service invocations.

## Issue reference

#1787 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests

2020-10-26 19:54 UTC, yaron2 requested changes

2020-10-26 19:54 UTC, yaron2 commented on tests/apps/perf/service_invocation_grpc/app.go
> +		Data:        []byte("ok"),
No data should be sent back

2020-10-26 19:55 UTC, yaron2 commented
@wmeints thanks for this PR. I have one comment for what's been pushed so far. we still need to have the test portion.

2020-10-27 09:27 UTC, wmeints commented
Thanks for the feedback!

I've got the test portion on my computer. I'm trying to figure out how to invoke the fortio tool so it uses grpc. I ran the test on my machine and it fails with a disconnect. Will have more time over the weekend to take a look and fix my test code.

2020-11-01 15:18 UTC, yaron2 commented
> Thanks for the feedback!
> 
> I've got the test portion on my computer. I'm trying to figure out how to invoke the fortio tool so it uses grpc. I ran the test on my machine and it fails with a disconnect. Will have more time over the weekend to take a look and fix my test code.

Any updates? You could also write your own test app instead of Fortio if the latter has a problem.

2020-11-01 17:13 UTC, wmeints commented
I'm actually working on the bits right now. I think I got beyond my initial problems. Will push an update when the test is working on my machine.

2020-11-01 19:04 UTC, closed without merging