Issue/2551
dapr/dapr pull request #2587
Opened 2020-12-15 19:42 UTC by juazasan

# Description

As for now Dapr returns escaped text in error message. For instance: "ERR_STATE_STORE_NOT_FOUND: state store unknown%20state%20store is not found"

However, error messages returned in HTTP API JSON response should not be HTTP escaped.

This PR ensure responses are not HTTP escaped.

## Issue reference

#2551 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2020-12-15 22:18 UTC, artursouza requested changes

2020-12-15 22:18 UTC, artursouza commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
%20 is just one of the many possible encoding for strings in the URL. Please, handle this at the request arrival instead. The issue is not only with the error message but it might cause issues where the name is valid but encoded, so the config is not found.

2020-12-15 22:19 UTC, artursouza commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
Also, use url decoding and not string replacement.

2020-12-16 06:59 UTC, juazasan commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
Thanks for the feedback. Will take a look at it.

2020-12-19 14:06 UTC, juazasan commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
Hi @artursouza I have updated the code and moved the solution to middleware. Please let me know your thoughts.

2020-12-22 04:31 UTC, artursouza commented
/ok-to-test

2020-12-22 06:42 UTC, artursouza commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
I will take a look at it tomorrow. I am curious about some other test scenarios. What if the name has "%2F" (it maps to "/")? I will try it out with some config names in standalone mode.

2020-12-22 08:26 UTC, juazasan commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
@artursouza Indeed. I was thinking of the same. My assumption was that all should be fine provided the request had been properly encoded. When it is not, indeed it may result in misleading situations. However, I do not see how we could address that as we cannot know what the original intend when encoding the request. Hope that makes sense.
On the other hand, I anticipated we may need to include additional test cases to cover other potential scenarios. The unit tests I added should allow us to easily add them. No need to do end to end testing but just add them to the unit tests.

2020-12-23 02:19 UTC, artursouza commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
I've make a POST request for state store with the following path: /v1.0/state/statestore%2Fhello

It turns out to return a wrong error message: `Method Not Allowed`

The right thing to do (IMO) is to have a utility method that can wrap the logic to get a value from the path, so code like this:
```txt
return reqCtx.UserValue(storeNameParam).(string)
```
would look like this:
```txt
return extractUserValue(reqCtx, storeParamName)
```

so `extractuserValue` would be a method that will do the unescaping.

/cc @yaron2

2020-12-23 07:16 UTC, juazasan commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
@artursouza IMHO the error you are reporting now is due to the request not properly formatted and the router not being able to identify the proper handler. POSTs to state stores do not allow the key to be included in the request URI:
{
	Methods: []string{fasthttp.MethodPost, fasthttp.MethodPut},
	Route:   "state/{storeName}",
	Version: apiVersionV1,
	Handler: a.onPostState,
},
Even in that case, the request is properly escaped and the %2F is replaced by just a "/". I have added one additional test case to the unit tests to demonstrate that. Then did some debugging with an end to end test and indeed the request was properly unescaped.

2020-12-23 19:54 UTC, artursouza commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
@juazasan `/v1.0/state/statestore%2Fhello` does not mean `hello` is the key. It means there is a state store named `statestore/hello`, so decoding `/v1.0/state/statestore%2Fhello` to `/v1.0/state/statestore/hello` is wrong because it changes the route not to match `statestore/{storeName}` anymore. With this PR, it is impossible for a state store to contain '/' in the name (encoded to '%2F', of course) while in the GRPC implementation it is possible.

Decoding needs to happen **after** route is processed. My recommendation is to do it when extracting the values of each parameter.

2020-12-23 19:59 UTC, juazasan commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
@artursouza I see. Will update the code then. One question though: Is this issue specific to state stores or the same needs to be applied to all the APIs / components? Thanks

2020-12-28 19:12 UTC, artursouza commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
This problem affects all http APIs.

2020-12-30 18:34 UTC, juazasan commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
@artursouza I have been working in an alternate implementation as per your recommendation. Have something already working for State and Secret Stores, and PubSub. Would love to please have your feedback and confirmation on applying the same for Actors (to parse ActorId) and Bindings (to parse the binding name). Not sure whether the same is needed for other parameters (keys, topics, etc.) and APIs (request invocation). Thanks.

2020-12-30 20:46 UTC, artursouza commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
This new approach is really good. Please, use the `getParameterValue()` for every URL parameter, including actor params.

2021-01-03 10:36 UTC, juazasan commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
Please @artursouza , one last question before completing the PR: I have been considering again using a middleware after the router as I think it simplifies the code base. Did a quick PoC which seems to work fine and would like to please have your thoughts. This alternate solution will require adding these few lines to the server.go module:

```go
func (s *server) unescapeRequestParametersHandler(next fasthttp.RequestHandler) fasthttp.RequestHandler {
	return func(ctx *fasthttp.RequestCtx) {
		parseError := false
		unescapeRequestParameters := func(parameter []byte, value interface{}) {
			switch value.(type) {
			case string:
				if !parseError {
					log.Info(fmt.Sprintf("parameter: %s, value: %v", parameter, value))
					parameterValue := fmt.Sprintf("%v", value)
					parameterUnescapedValue, err := url.QueryUnescape(parameterValue)
					if err == nil {
						ctx.SetUserValueBytes(parameter, parameterUnescapedValue)
					} else {
						parseError = true
						errorMessage := fmt.Sprintf("Failed to unescape request parameter %s with value %v. Error: %s", parameter, value, err.Error())
						log.Debug(errorMessage)
						ctx.Error(errorMessage, fasthttp.StatusBadRequest)
					}
				}
			}
		}
		ctx.VisitUserValues(unescapeRequestParameters)

		if !parseError {
			next(ctx)
		}
	}
}

func (s *server) getRouter(endpoints []Endpoint) *routing.Router {
	router := routing.New()
	parameterFinder, _ := regexp.Compile("/{.*}")
	for _, e := range endpoints {
		path := fmt.Sprintf("/%s/%s", e.Version, e.Route)
		for _, m := range e.Methods {
			pathIncludesParameters := parameterFinder.MatchString(path)
			if pathIncludesParameters {
				router.Handle(m, path, s.unescapeRequestParametersHandler(e.Handler))
			} else {
				router.Handle(m, path, e.Handler)
			}
		}
	}
	return router
}
```

2021-01-05 01:51 UTC, artursouza commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
That sounds promising. I like that approach too.

2021-01-05 17:13 UTC, juazasan commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
@artursouza Have just submitted the middleware code including the unit tests.

2021-01-06 00:39 UTC, artursouza requested changes

2021-01-06 00:39 UTC, artursouza commented on pkg/http/server.go
> +					log.Info(fmt.Sprintf("parameter: %s, value: %v", parameter, value))
No need to log this. Unless you log debug.

2021-01-06 00:39 UTC, artursouza commented
/ok-to-test

2021-01-06 00:40 UTC, artursouza commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
This is great solution. Please, remove the unnecessary logging.

2021-01-06 01:33 UTC, artursouza approved these changes

2021-01-06 01:34 UTC, artursouza commented on pkg/http/responses.go
> +	respondWithJSON(ctx, code, bytes.ReplaceAll(b, []byte("%20"), []byte(" ")))
I just removed it directly in your branch. I am merging the change now. Thanks for your contribution.

2021-01-06 02:31 UTC, artursouza commented
I validated it locally and it works. I tested with an invalid state store name and also with one that exists but has "/" in the name. It works perfectly.

2021-01-06 02:34 UTC, yaron2 commented
Thanks for this @juazasan!

2021-01-06 02:48 UTC, merged