fix error log
dapr/dapr pull request #2633
Opened 2021-01-05 23:47 UTC by vinayada1

# Description

Fix unwanted error message

#2468 

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #2468 
## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-01-06 16:19 UTC, tcnghia commented on pkg/runtime/runtime.go
> +			if !subscribed {
```suggestion
			if !a.isAppSubscribedToBinding(name) {
```

2021-01-06 16:19 UTC, tcnghia commented on pkg/runtime/runtime.go
> +			if !subscribed {
I didn't see `subscribed` used anywhere, and `!a.isAppSubscribedToBinding(name)` is as readable.

2021-01-06 18:22 UTC, yaron2 requested changes

2021-01-06 18:22 UTC, yaron2 commented on pkg/runtime/runtime.go
> +				log.Infof("app-id=%s has not subscribed to binding %s.", a.runtimeConfig.ID, name)
Since this log is per Dapr deployment (app-id), I think we can remove the `app-id` portion here. this is consistent with other logs in `daprd`

2021-01-07 22:44 UTC, yaron2 approved these changes
lgtm

2021-01-07 22:44 UTC, merged