feature(actors): add CreateTimer unit tests
dapr/dapr pull request #2748
Opened 2021-01-29 12:54 UTC by 1046102779

Add actors/timer UT

2021-02-03 06:41 UTC, 1046102779 commented
please @artursouza this PR

2021-02-05 18:40 UTC, artursouza commented
/ok-to-test

2021-02-05 22:00 UTC, artursouza requested changes

2021-02-05 22:00 UTC, artursouza commented on pkg/actors/actors_test.go
> +	time.Sleep(8 * time.Second)
Can this test that the timer call actually happened. Make it more frequent, so it does not need to sleep for 8 seconds. That is a lot of time.

2021-03-19 06:04 UTC, artursouza commented
@1046102779  There are some conflicts now in actors_test.go.

2021-04-28 17:11 UTC, artursouza requested changes
I am still concerned about using Sleep() in unit tests.

2021-04-28 17:11 UTC, artursouza commented on pkg/actors/actors_test.go
> +	time.Sleep(3 * time.Second)
Please, modify the test so it does not depend on sleep and add validation.

/cc @pkedy

2021-07-01 17:49 UTC, closed without merging