optimize(http): reduce repetitive secretstore codes
dapr/dapr pull request #2841
Opened 2021-02-23 13:54 UTC by 1046102779

merge onBulkGetSecret and onGetSecret codes

2021-02-24 04:12 UTC, 1046102779 commented
I didn't find that  http/secretstore codes is changed, it will have a negative impact on unit testing TestBindings

2021-02-25 07:33 UTC, artursouza requested changes

2021-02-25 07:33 UTC, artursouza commented on pkg/http/api.go
> +		log.Debug(msg)
This will cause debugging to happen twice: here and at the caller.

2021-02-25 07:33 UTC, artursouza commented on pkg/http/api.go
> +		log.Debug(msg)
This will cause debugging to happen twice: here and at the caller.

2021-02-25 17:19 UTC, artursouza approved these changes

2021-02-26 02:02 UTC, merged