[WIP] Consul nameresolution component - runtime changes
dapr/dapr pull request #2904
Opened 2021-03-09 15:28 UTC by a-elsheikh

# Description

This PR contains the supporting changes for the new consul nameresolution component. This also includes the ability to configure the target nameresolution component and parse environment variables from config in the runtime.

## Issue reference

dapr/components-contrib#749

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-03-19 17:31 UTC, yaron2 requested changes

2021-03-19 17:31 UTC, yaron2 commented on pkg/runtime/runtime.go
> +		resolverVersion = "v1"
Can `v1` be a constant somewhere?

2021-03-22 10:00 UTC, a-elsheikh commented on pkg/runtime/runtime.go
> +		resolverVersion = "v1"
done, have a look

2021-04-12 14:37 UTC, pkedy commented
@a-elsheikh I got this working in Kubernetes but I had to make some changes. Since I don't have access to push to your branch, I'm attaching this diff/patch. [consul_patch.diff.txt](https://github.com/dapr/dapr/files/6297509/consul_patch.diff.txt). Please take a look. Thanks!

2021-04-13 09:26 UTC, a-elsheikh commented
> @a-elsheikh I got this working in Kubernetes but I had to make some changes. Since I don't have access to push to your branch, I'm attaching this diff/patch. [consul_patch.diff.txt](https://github.com/dapr/dapr/files/6297509/consul_patch.diff.txt). Please take a look. Thanks!

Nice! I've applied it and pushed

2021-04-21 17:13 UTC, yaron2 commented
Lets merge the contrib PR and update the branch here so we can run e2e.

/cc @pkedy

2021-04-21 17:29 UTC, yaron2 commented
@a-elsheikh we merged the components-contrib PR.

Can you please make the following changes?

1. Run `go get -u github.com/dapr/components-contrib@master`
2. Run `go mod tidy`
3. Push your changes

2021-04-22 09:04 UTC, a-elsheikh commented
> @a-elsheikh we merged the components-contrib PR.
> 
> Can you please make the following changes?
> 
> 1. Run `go get -u github.com/dapr/components-contrib@master`
> 2. Run `go mod tidy`
> 3. Push your changes

done

2021-04-22 16:40 UTC, yaron2 approved these changes

2021-04-22 16:42 UTC, yaron2 commented
@a-elsheikh the only thing left to do now is open a docs issue and PR to explain how to configure and use the Consul component.

2021-04-22 16:53 UTC, a-elsheikh commented
> @a-elsheikh the only thing left to do now is open a docs issue and PR to explain how to configure and use the Consul component.

yep, that already exists - dapr/docs#1408

2021-04-22 21:50 UTC, merged

2021-04-22 22:32 UTC, pkedy commented
Congratulations @a-elsheikh! I know this was a long time coming. Apologies for the delay.

2021-04-23 08:43 UTC, a-elsheikh commented
> Congratulations @a-elsheikh! I know this was a long time coming. Apologies for the delay.

@pkedy @yaron2 thank you both for your guidance, I'll start having a look at the docs now 😄