optimize: directly use default metrics register
dapr/dapr pull request #3053
Opened 2021-04-14 08:01 UTC by 1046102779

![image](https://user-images.githubusercontent.com/20457624/114675322-ae211600-9d3a-11eb-9e5d-244e61f5efda.png)

2021-04-27 06:22 UTC, artursouza submitted a review, later dismissed

2021-04-27 23:20 UTC, artursouza commented
@1046102779 Please, resolve conflict.

2021-05-04 05:26 UTC, artursouza requested changes

2021-05-04 05:26 UTC, artursouza commented on pkg/metrics/exporter.go
> -	registry.MustRegister(prom.NewProcessCollector(prom.ProcessCollectorOpts{}))
What about these 2 collectors? Are they included by default?

2021-05-06 01:58 UTC, 1046102779 commented on pkg/metrics/exporter.go
> -	registry.MustRegister(prom.NewProcessCollector(prom.ProcessCollectorOpts{}))
yes。

2021-05-07 16:32 UTC, artursouza approved these changes

2021-05-07 16:53 UTC, yaron2 approved these changes

2021-05-07 17:31 UTC, merged