Add E2E tests for Kubernetes 1.20/1.21
dapr/dapr pull request #3367
Opened 2021-06-28 15:50 UTC by dmitsh

# Description

Add E2E tests for Kubernetes 1.20/1.21

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #3366

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-06-28 16:38 UTC, dmitsh commented
/assign

2021-06-28 16:40 UTC, wcs1only submitted a review, later dismissed
LGTM, so long as the new tests pass.

2021-06-28 16:44 UTC, wcs1only commented
One note: if we hit any kind of rate limiting on KinD builds, we probably don't need HA-mode + non-HA-mode for all 3/5 versions. But, we can reduce the number of non-HA-mode KinD runs at a future time, only if necessary.

2021-06-29 07:42 UTC, daixiang0 commented
lgtm

btw, do we have a doc comment lowest k8s support version?

2021-06-29 14:09 UTC, dmitsh commented
> lgtm
> 
> btw, do we have a doc comment lowest k8s support version?

We are discussing it here: https://github.com/dapr/dapr/issues/3348

2021-06-30 21:40 UTC, yaron2 commented
Can we remove 1.17? I want to align to supported k8s versions.

2021-06-30 21:45 UTC, yaron2 requested changes

2021-06-30 21:45 UTC, yaron2 commented on .github/workflows/dapr-e2e-kind.yml
> +        - v1.17.17
Remove

2021-06-30 21:45 UTC, yaron2 commented on .github/workflows/dapr-e2e-kind.yml
> +        - v1.18.19
Remove

2021-07-01 00:02 UTC, yaron2 approved these changes
lgtm

2021-07-01 00:51 UTC, yaron2 approved these changes
lgtm

2021-07-01 00:54 UTC, merged