ci: do build before setup cluster
dapr/dapr pull request #3425
Opened 2021-07-12 09:07 UTC by daixiang0

Signed-off-by: Long Dai <long0dai@foxmail.com>

# Description

Since e2e-kind tests do not depend on the build, if the build failed, we need to wait much time to get result, so adjust order.

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-07-12 18:19 UTC, artursouza requested changes

2021-07-12 18:19 UTC, artursouza commented on .github/workflows/dapr-e2e-kind.yml
> +        docker network connect "kind" $REGISTRY_NAME
It uses kind here.

2021-07-13 01:14 UTC, daixiang0 commented on .github/workflows/dapr-e2e-kind.yml
> +        docker network connect "kind" $REGISTRY_NAME
Oh, I miss it.

2021-07-13 01:15 UTC, daixiang0 commented on .github/workflows/dapr-e2e-kind.yml
> +        docker network connect "kind" $REGISTRY_NAME
Oh, I miss it.

2021-07-13 01:15 UTC, closed without merging