runtime: support unix domain socket
dapr/dapr pull request #3529
Opened 2021-08-09 02:03 UTC by daixiang0

Signed-off-by: Long <long0dai@foxmail.com>

# Description

Support unix domain socket.

## Issue reference

Please reference the issue this PR will close: #2864

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-08-09 02:51 UTC, daixiang0 commented
after build:
1. run with hello-world example in `quick-start`
`daprd --app-id nodeapp  --app-protocol http --components-path /root/.dapr/components --metrics-port 39497 --dapr-http-max-request-size -1 --app-port 3000 --placement-host-address localhost:50005 --config /root/.dapr/config.yaml --enable-domain-socket`
2. test
`curl  --unix-socket /tmp/nodeapp-http.socket  http://127.0.0.1:34273/v1.0/state/statestore/order`

2021-08-09 03:47 UTC, yaron2 commented
I'm really happy to see this PR landing. Notice tests are failing.

2021-08-11 07:35 UTC, daixiang0 commented
@artursouza @wcs1only I have set this option false as default, while it is true in the test, is it a potential bug for cli?

2021-08-13 01:30 UTC, daixiang0 commented
@artursouza I have checked codes, in fact since do not enable domain socket, all tests should pass like before, while redis always can not connect, see https://github.com/dapr/dapr/pull/3529/checks?check_run_id=3309572217#step:17:851. Could help take a look here?

2021-08-14 00:22 UTC, artursouza requested changes
LGTM overall. This would need changes in the CLI, docs and SDKs too.

2021-08-14 00:22 UTC, artursouza commented on pkg/grpc/server.go
> +		socket := fmt.Sprintf("/tmp/%s-grpc.socket", s.config.AppID)
Please, use "dapr-" in the filename to make it clear that his is for dapr.

2021-08-14 00:22 UTC, artursouza commented on pkg/http/server.go
> +			socket := fmt.Sprintf("/tmp/%s-http.socket", s.config.AppID)
same. Use "dapr-".

2021-08-14 00:22 UTC, artursouza commented on pkg/runtime/runtime.go
> +			os.Remove(fmt.Sprintf("/tmp/%s-%s.socket", a.runtimeConfig.ID, s))
"dapr-"

2021-08-16 01:26 UTC, daixiang0 commented
@artursouza I think CLI changes need to wait this merged if there is any e2e based on `daprd`, docs changes as well, SDK is the last step while I do not familiar with other languages, I will create issues to track it.

2021-08-16 07:12 UTC, daixiang0 commented on pkg/runtime/runtime.go
> +			os.Remove(fmt.Sprintf("/tmp/%s-%s.socket", a.runtimeConfig.ID, s))
All fixed.

2021-08-16 07:41 UTC, daixiang0 commented
sorry for force push since flaky tests, if there is a better way to re-run tests, please tell me, thanks.

2021-08-19 20:44 UTC, greenie-msft commented
@artursouza, should this be included in the 1.4 milestone?

2021-08-19 23:10 UTC, artursouza commented
> @artursouza, should this be included in the 1.4 milestone?


I prefer to add community contributions to the milestone when they get merged.

2021-08-19 23:14 UTC, artursouza approved these changes

2021-08-19 23:14 UTC, artursouza commented
Please, create tracking issues in CLI and SDKs.

2021-08-19 23:15 UTC, artursouza commented
@yaron2  @greenie-msft  @orizohar   For this feature to be announced, we would need to have support in at least CLI and one SDK.

2021-08-20 01:36 UTC, yaron2 commented
> @yaron2 @greenie-msft @orizohar For this feature to be announced, we would need to have support in at least CLI and one SDK.

Ok, but why? For example, cant users directly call via the socket if using their own gRPC client?

2021-08-20 16:51 UTC, artursouza commented
> > @yaron2 @greenie-msft @orizohar For this feature to be announced, we would need to have support in at least CLI and one SDK.
> 
> 
> 
> Ok, but why? For example, cant users directly call via the socket if using their own gRPC client?


Yes, but we should make it a first class feature with flags from CLI and config in the SDKs. Otherwise, people might not use it.

2021-08-20 16:54 UTC, yaron2 commented
> > > @yaron2 @greenie-msft @orizohar For this feature to be announced, we would need to have support in at least CLI and one SDK.
> > 
> > 
> > Ok, but why? For example, cant users directly call via the socket if using their own gRPC client?
> 
> Yes, but we should make it a first class feature with flags from CLI and config in the SDKs. Otherwise, people might not use it.

Ok, just making sure there isn't some special config that needs to be done for this, and that regular gRPC/HTTP clients can use this.

2021-08-20 18:41 UTC, merged