daprd wait app ready
dapr/dapr pull request #3605
Opened 2021-09-01 09:58 UTC by theonefx

# Description

daprd wait app ready
- 1. via http path check
- 2. via k8s readiness probe

## Issue reference

this is a part of issue : https://github.com/dapr/dapr/issues/2918

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-09-01 12:53 UTC, jjcollinge commented on pkg/runtime/runtime.go
> +	log.Infof("wait applicatoin ready, continue init")
nit: typo

2021-09-02 00:26 UTC, daixiang0 commented on tests/config/dapr_kafka_bindings_custom_route.yaml
> +    # Kafka broker connection setting
seems no truly changes here.

2021-09-02 01:38 UTC, theonefx commented on tests/config/dapr_kafka_bindings_custom_route.yaml
> +    # Kafka broker connection setting
you are rignt, i will revert it.

2021-09-02 02:27 UTC, theonefx commented on tests/config/dapr_kafka_bindings_custom_route.yaml
> +    # Kafka broker connection setting
revert done

2021-09-02 06:08 UTC, theonefx commented on pkg/runtime/runtime.go
> +	log.Infof("wait applicatoin ready, continue init")
it's a spelling mistake. fixed ^_^

2021-09-15 23:55 UTC, pkedy reviewed
This is an interesting approach! I see a new resource permission is required in the ClusterRoleBinding. Hypothetically, how does the code handle not having this permission?

2021-09-17 02:13 UTC, theonefx commented
> This is an interesting approach! I see a new resource permission is required in the ClusterRoleBinding. Hypothetically, how does the code handle not having this permission?

I've tried, and I got an error message with no permissions. So, I have to add the permission definition.

2021-09-27 22:06 UTC, artursouza requested changes
/cc @yaron2

2021-09-27 22:06 UTC, artursouza commented on pkg/runtime/wait.go
> +	if a.runtimeConfig.WaitingProbe != "" {
Doesn't K8s already have readiness check? I see that this is helpful for Standalone mode but this is too specific - it is on HTTP only (does not support gRPC) and content-type is forced to JSON. Can the waitingProbe (maybe readinessCheck is a better name here) be configured in the Configuration CRD?

Again, this check only adds value to standalone mode.

2021-09-27 22:20 UTC, yaron2 requested changes

2021-09-27 22:20 UTC, yaron2 commented on pkg/injector/pod_patch.go
> +				Name: "POD_NAME",
We need to find another way to either pass the pod name to the container or identify the pod in the operator. This uses the FieldPath ref (Downward API) which is not supported on platforms like Virtual Kubelet.

2021-09-27 22:21 UTC, yaron2 commented
Added comment, looks good otherwise.

2021-10-18 02:21 UTC, daixiang0 commented
@theonefx please resolve conflicts.

2021-11-30 16:27 UTC, yaron2 commented
Ping @theonefx

2021-12-31 02:01 UTC, daixiang0 commented
ping @theonefx

2022-03-08 02:54 UTC, closed without merging