Add tolerations support to Helm Chart
dapr/dapr pull request #3663
Opened 2021-09-14 08:20 UTC by denis111

# Description

Added tolerations support to values of Helm Chart. There was only nodeSelector available but we can't schedule pods on tainted nodes with with only nodeSelector. Most of other helm charts around have tolerations support through values.

## Issue reference

Please reference the issue this PR will close: #3534

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

I've already applied tolerations in this PR on our production Dapr.

2021-09-15 01:06 UTC, daixiang0 commented
lgtm

2021-09-17 11:09 UTC, denis111 commented
"E2E tests on KinD / e2e" fail is not my fault ;)

2021-09-18 00:53 UTC, daixiang0 submitted a review, later dismissed

2021-09-20 13:51 UTC, denis111 commented
I see that the chart in master branch is behind the one in release-1.4, how we can fix it?

2021-09-23 03:39 UTC, daixiang0 commented
Not sure the best way to do it, /cc @artursouza

2021-09-23 16:49 UTC, yaron2 commented
@denis111 please resolve conflicts.

2021-09-28 00:39 UTC, artursouza requested changes

2021-09-28 00:39 UTC, artursouza commented on charts/dapr/Chart.yaml
> -version: 1.4.0
These are only updated during release, please, revert.

2021-09-28 00:39 UTC, artursouza commented on charts/dapr/charts/dapr_dashboard/Chart.yaml
> +version: 0.8.1
These are only updated during release, please, revert.

2021-09-28 00:39 UTC, artursouza commented on charts/dapr/charts/dapr_operator/Chart.yaml
> +version: 1.4.1
These are only updated during release, please, revert.

2021-09-28 00:39 UTC, artursouza commented on charts/dapr/charts/dapr_placement/Chart.yaml
> +version: 1.4.1
These are only updated during release, please, revert.

2021-09-28 00:39 UTC, artursouza commented on charts/dapr/charts/dapr_sentry/Chart.yaml
> +version: 1.4.1
These are only updated during release, please, revert.

2021-09-28 00:39 UTC, artursouza commented on charts/dapr/charts/dapr_sidecar_injector/Chart.yaml
> +version: 1.4.1
These are only updated during release, please, revert.

2021-09-28 09:56 UTC, denis111 commented
@artursouza Ok, done. But I've just followed helm best practices for semver...

2021-10-01 03:57 UTC, cvictory submitted a review, later dismissed
LGTM

2021-10-01 22:55 UTC, denis111 commented
@artursouza should I do anything more or this PR is ready to be approved?

2021-10-01 23:15 UTC, artursouza approved these changes

2021-10-02 00:06 UTC, merged