Add ut for injector handleRequest
dapr/dapr pull request #3720
Opened 2021-09-28 05:11 UTC by qmhu

# Description
Add unit test for injector's function handleRequest.
Change injector's client from kubernetes.Clientset to kubernetes.Interface to let unit test mock test client.

## Issue reference

Please reference the issue this PR will close: #_[3708]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-09-28 05:18 UTC, daixiang0 requested changes

2021-09-28 05:18 UTC, daixiang0 commented on pkg/injector/injector_test.go
> +		TLSCertFile:            "a",
Please use fake name like "test-xx" rather than those, same below.

2021-09-28 05:18 UTC, daixiang0 commented on pkg/injector/injector_test.go
> +			"application/json",
Please use constant, same below.

2021-09-28 05:33 UTC, qmhu commented on pkg/injector/injector.go
> +	kubeClient   kubernetes.Interface
kubernetes.Interface is an interface, does it bring an additional object copy? 
use client.Interface seems a more common choice for controllers in k8s.  
WDYT

2021-09-28 06:38 UTC, qmhu commented on pkg/injector/injector_test.go
> +			"application/json",
addressed

2021-09-28 06:39 UTC, qmhu commented on pkg/injector/injector_test.go
> +		TLSCertFile:            "a",
addressed

2021-09-30 04:44 UTC, yaron2 commented
@daixiang0 are you good to merge this?

2021-09-30 04:47 UTC, daixiang0 commented on pkg/injector/injector.go
> +	kubeClient   kubernetes.Interface
ok.

2021-09-30 04:49 UTC, daixiang0 approved these changes
LGTM.

/cc @yaron2

2021-09-30 05:24 UTC, yaron2 commented
@qmhu there's a test failing on Windows:

```
=== FAIL: pkg/injector TestHandleRequest (0.00s)
panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: The requested service provider could not be loaded or initialized. [recovered]
	panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: The requested service provider could not be loaded or initialized.

goroutine 81 [running]:
testing.tRunner.func1.2({0x115dd20, 0xc0002dc970})
	C:/hostedtoolcache/windows/go/1.17.1/x64/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.17.1/x64/src/testing/testing.go:1212 +0x218
panic({0x115dd20, 0xc0002dc970})
	C:/hostedtoolcache/windows/go/1.17.1/x64/src/runtime/panic.go:1038 +0x215
net/http/httptest.newLocalListener()
	C:/hostedtoolcache/windows/go/1.17.1/x64/src/net/http/httptest/server.go:71 +0xe9
net/http/httptest.NewUnstartedServer(...)
	C:/hostedtoolcache/windows/go/1.17.1/x64/src/net/http/httptest/server.go:117
net/http/httptest.NewServer({0x15461e0, 0xc0002dc940})
	C:/hostedtoolcache/windows/go/1.17.1/x64/src/net/http/httptest/server.go:104 +0x2d
github.com/dapr/dapr/pkg/injector.TestHandleRequest(0xc00021a4e0)
	D:/a/dapr/dapr/pkg/injector/injector_test.go:602 +0xcbb
testing.tRunner(0xc00021b040, 0x141b038)
	C:/hostedtoolcache/windows/go/1.17.1/x64/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.17.1/x64/src/testing/testing.go:1306 +0x35a
```

2021-09-30 16:52 UTC, yaron2 commented
@wcs1only look at the error above - could it be our Windows agent isn't allowed to open tcp6 sockets?

2021-10-01 03:14 UTC, qmhu commented
> @qmhu there's a test failing on Windows:
> 
> ```
> === FAIL: pkg/injector TestHandleRequest (0.00s)
> panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: The requested service provider could not be loaded or initialized. [recovered]
> 	panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: The requested service provider could not be loaded or initialized.
> 
> goroutine 81 [running]:
> testing.tRunner.func1.2({0x115dd20, 0xc0002dc970})
> 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/testing/testing.go:1209 +0x24e
> testing.tRunner.func1()
> 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/testing/testing.go:1212 +0x218
> panic({0x115dd20, 0xc0002dc970})
> 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/runtime/panic.go:1038 +0x215
> net/http/httptest.newLocalListener()
> 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/net/http/httptest/server.go:71 +0xe9
> net/http/httptest.NewUnstartedServer(...)
> 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/net/http/httptest/server.go:117
> net/http/httptest.NewServer({0x15461e0, 0xc0002dc940})
> 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/net/http/httptest/server.go:104 +0x2d
> github.com/dapr/dapr/pkg/injector.TestHandleRequest(0xc00021a4e0)
> 	D:/a/dapr/dapr/pkg/injector/injector_test.go:602 +0xcbb
> testing.tRunner(0xc00021b040, 0x141b038)
> 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/testing/testing.go:1259 +0x102
> created by testing.(*T).Run
> 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/testing/testing.go:1306 +0x35a
> ```

@yaron2 Cannot reproduce the error in my windows laptop..., so i'd like to retrigger testing to see what's going on.

2021-10-01 04:20 UTC, yaron2 commented
> > @qmhu there's a test failing on Windows:
> > ```
> > === FAIL: pkg/injector TestHandleRequest (0.00s)
> > panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: The requested service provider could not be loaded or initialized. [recovered]
> > 	panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: The requested service provider could not be loaded or initialized.
> > 
> > goroutine 81 [running]:
> > testing.tRunner.func1.2({0x115dd20, 0xc0002dc970})
> > 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/testing/testing.go:1209 +0x24e
> > testing.tRunner.func1()
> > 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/testing/testing.go:1212 +0x218
> > panic({0x115dd20, 0xc0002dc970})
> > 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/runtime/panic.go:1038 +0x215
> > net/http/httptest.newLocalListener()
> > 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/net/http/httptest/server.go:71 +0xe9
> > net/http/httptest.NewUnstartedServer(...)
> > 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/net/http/httptest/server.go:117
> > net/http/httptest.NewServer({0x15461e0, 0xc0002dc940})
> > 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/net/http/httptest/server.go:104 +0x2d
> > github.com/dapr/dapr/pkg/injector.TestHandleRequest(0xc00021a4e0)
> > 	D:/a/dapr/dapr/pkg/injector/injector_test.go:602 +0xcbb
> > testing.tRunner(0xc00021b040, 0x141b038)
> > 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/testing/testing.go:1259 +0x102
> > created by testing.(*T).Run
> > 	C:/hostedtoolcache/windows/go/1.17.1/x64/src/testing/testing.go:1306 +0x35a
> > ```
> 
> @yaron2 Cannot reproduce the error in my windows laptop..., so i'd like to retrigger testing to see what's going on.

Re-triggered. It might be that the Windows agent doesn't allow ipv6.

2021-10-01 15:58 UTC, qmhu commented
I just reproduce the error , the unit test in `config_test.go` clean all envs and break the server starting when testing in Windows~ 
@yaron2

2021-10-01 16:45 UTC, yaron2 approved these changes
lgtm

2021-10-02 14:50 UTC, merged