Update dashboard chart: use registry and imagePullSecrets from global values
dapr/dapr pull request #3843
Opened 2021-11-03 18:33 UTC by fjvela

# Description
Update dashboard chart: use registry and imagePullSecrets from global values

## Issue reference
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/3841

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

![image](https://user-images.githubusercontent.com/5806680/140171376-539b51ea-eba6-4c29-a842-f29750a3d712.png)
![image](https://user-images.githubusercontent.com/5806680/140171483-7c09e42a-a3a7-4b87-b0e8-2e4112333ade.png)

2021-11-03 19:47 UTC, artursouza approved these changes

2021-11-03 19:48 UTC, artursouza requested changes
It broke the build.

2021-11-04 04:17 UTC, fjvela commented
> It broke the build.

I saw it. Dashboard image isn't found.

E2E test build all images and push them to a local registry. Dasboard image is built ourside.....

Let my think another solution.

2021-11-08 06:37 UTC, daixiang0 approved these changes

2021-11-14 19:18 UTC, fjvela commented
I close the PR.  No solution for this.

I'll create another PR and I add some examples in documentation.

2021-11-14 19:18 UTC, closed without merging