use addDate to support leap year & leap month
dapr/dapr pull request #4027
Opened 2021-12-14 11:45 UTC by theonefx

# Description

## Issue reference
https://github.com/dapr/dapr/issues/3995

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-12-16 02:44 UTC, daixiang0 commented
Please add tests for leap year/month.

2021-12-16 06:22 UTC, theonefx commented
> Please add tests for leap year/month.

done

2021-12-16 06:25 UTC, daixiang0 commented on pkg/actors/actors_test.go
> +	t.Run("parse ISO 8610 with leap yean", func(t *testing.T) {
typo `yean` here.

2021-12-16 12:07 UTC, theonefx commented on pkg/actors/actors_test.go
> +	t.Run("parse ISO 8610 with leap yean", func(t *testing.T) {
done

2021-12-17 07:14 UTC, theonefx commented
@artursouza @yaron2

2021-12-18 00:17 UTC, yaron2 requested changes

2021-12-18 00:17 UTC, yaron2 commented on pkg/actors/actors.go
> +		yeads, months, days int
typo - change `yeads` to `years`.

2021-12-19 13:45 UTC, theonefx commented on pkg/actors/actors.go
> +		yeads, months, days int
done

2021-12-22 01:20 UTC, yaron2 approved these changes
lgtm

2021-12-22 01:20 UTC, merged