warn users of mTLS certification expiration
dapr/dapr pull request #4064
Opened 2021-12-28 09:03 UTC by tanvigour

# Description

Issue warning for mTLS expiration

## Issue reference

Please reference the issue this PR will close: #3940

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-12-28 18:27 UTC, yaron2 requested changes

2021-12-28 18:27 UTC, yaron2 commented on pkg/sentry/server/server.go
> +	if serverCertTTL <= 30 {
What is `30` here? is it supposed to be days? If it's days, then:

1. It won't work as the value of `time.Duration` doesn't represent days
2. the error message should be "The root CA cert is about to expire in %s days"

2021-12-28 18:28 UTC, yaron2 commented on pkg/sentry/server/server.go
> +	if serverCertTTL <= 30 {
Also, please add a test for this.

2022-01-08 07:59 UTC, Taction commented on pkg/sentry/server/server.go
> +	}
Some minor changes. You should use `Warnf` here, and `%f` to format this float value.
```
        if hoursLeft := serverCertTTL.Hours(); hoursLeft <= 720 {
		log.Warnf("The root CA cert is about to expire in %f days", hoursLeft/24)
	}
```

2022-01-08 08:01 UTC, Taction commented
@tanvigour Also please fix DCO issues.

2022-03-14 17:35 UTC, berndverst commented
I think we can abandon this PR in favor of https://github.com/dapr/dapr/pull/4328 which was merged. The proper way to be warned is to watch Sentry logs and enable alerting based on the Sentry logs.

Also there are other changes in the CLI that provide additional warnings there.

@artursouza @daixiang0 @yaron2 I recommend closing this PR here.

2022-03-14 17:42 UTC, closed without merging