Add json util to unmarshal numbers into int/float
dapr/dapr pull request #4093
Opened 2022-01-05 07:35 UTC by hueifeng

# Description

Details are as follows: https://github.com/dapr/dapr/pull/4069

## Issue reference

Please reference the issue this PR will close: #3837 #4026  

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-01-07 01:33 UTC, artursouza commented
E2E tests are not passing on this PR. Moving to 1.7

2022-01-07 01:38 UTC, yaron2 commented
@hueifeng please see that e2e tests are failing. Need to understand why and fix.

2022-01-07 03:40 UTC, yaron2 commented
@hueifeng see linter failures. I recommend using an editor like VS code with the Go extension to make sure all the linter requirements are in place.

2022-01-07 06:11 UTC, yaron2 commented
@hueifeng linter and tests issues..

2022-01-07 07:37 UTC, hueifeng commented
@yaron2 It looks like it's working.
![image](https://user-images.githubusercontent.com/34702552/148508735-0bb7a8c2-5521-41ab-9342-1d6753300a1c.png)

2022-01-07 07:42 UTC, yaron2 commented
> @yaron2 It looks like it's working. ![image](https://user-images.githubusercontent.com/34702552/148508735-0bb7a8c2-5521-41ab-9342-1d6753300a1c.png)

Search for "Check failure" here: https://github.com/dapr/dapr/pull/4093/files. it'll show you exactly which files need what formatter.

2022-01-11 17:31 UTC, yaron2 commented
@hueifeng please run the following:

(Make sure you're using Go.17.x)

```
go install golang.org/x/tools/cmd/goimports@latest

goimports -w -local ./pkg/channel/testing/grpc_channel_server_mock.go
goimports -w -local ./pkg/injector/injector_test.go
goimports -w -local ./tests/apps/pubsub-subscriber_grpc/app.go

go install mvdan.cc/gofumpt@latest

gofumpt -w ./pkg/grpc/api.go
gofumpt -w ./pkg/grpc/api.go
gofumpt -w ./pkg/http/api.go
```

2022-01-12 17:34 UTC, yaron2 commented
@hueifeng we are almost there! down to 3 failures from 6.

Please run the following:

```
goimports -w -local ./pkg/operator/api/api.go
goimports -w -local ./pkg/components/kubernetes_loader_test.go
goimports -w -local ./pkg/expr/expr.go
```

2022-01-14 05:13 UTC, artursouza commented
Moving this to 1.7 since we are cutting RC1 for 1.6.0. I can still cherry-pick it to 1.6 if this is merged prior to the release.

2022-01-14 05:42 UTC, hueifeng commented
There is a conflict，I only have only read only permissions, there is no write permission.

2022-01-14 06:06 UTC, daixiang0 commented
@hueifeng you can do it locally then `git push`.

2022-01-14 17:03 UTC, yaron2 requested changes

2022-01-14 17:03 UTC, yaron2 commented on pkg/http/api.go
> +	mtdBytes, err := jsoniter.Marshal(mtd)
we need to remove `jsoniter` here

2022-01-16 07:59 UTC, Taction commented on pkg/http/api.go
>  		qresp.Results[i].Data = jsoniter.RawMessage(resp.Results[i].Data)
please replace `jsoniter.RawMessage` with `json.RawMessage`. So we can completely remove the package `github.com/json-iterator/go`.

2022-03-24 08:15 UTC, closed without merging