log warning when error connecting to placement service
dapr/dapr pull request #4110
Opened 2022-01-10 07:15 UTC by patrickxiong

Signed-off-by: Patrick.Xiong <patrick.xiong@gmail.com>

# Description

Change the log level from debug to warn when error connecting to placement service

## Issue reference

Please reference the issue this PR will close: #_[2896]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ *] Code compiles correctly
* [ ] Created/updated tests
* [ *] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-01-11 04:05 UTC, beiwei30 approved these changes
LGTM

2022-03-18 22:15 UTC, mukundansundar approved these changes

2022-03-18 22:26 UTC, yaron2 commented
This will result in a swarm of error messages showing every 500ms. Do we want that?

cc @artursouza

2022-06-22 03:23 UTC, artursouza requested changes

2022-06-22 03:23 UTC, artursouza commented on pkg/actors/internal/placement.go
> +			log.Warnf("error connecting to placement service: %v", err)
This will make it too verbose.

2022-10-07 16:37 UTC, closed without merging