Add acl wildcard support and test
dapr/dapr pull request #4238
Opened 2022-02-14 05:15 UTC by CrazyHZM

Signed-off-by: crazyhzm <crazyhzm@gmail.com>

# Description

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-02-15 03:19 UTC, beiwei30 requested changes

2022-02-15 03:19 UTC, beiwei30 commented on tests/apps/service_invocation/app.go
> +	router.HandleFunc("/grpcwithouthttpverbtogrpctest", grpcWithoutHttpVerbToGrpcTest).Methods("POST")
'/grpctogrpcwithoutverb' and 'grpcToGrpcWithoutVerb' should be better.

2022-02-15 03:19 UTC, beiwei30 commented on tests/apps/service_invocation/app.go
> +func grpcWithoutHttpVerbToGrpcTest(w http.ResponseWriter, r *http.Request) {
This function looks almost same as 'grpcToGrpcTest'. Suggest to reuse instead of dup.

2022-02-21 20:09 UTC, yaron2 commented
@CrazyHZM there's a failing unit test `TestIsOperationAllowedByAccessControlPolicy`. Fix that and we can merge :)

2022-02-28 22:16 UTC, yaron2 approved these changes

2022-02-28 22:19 UTC, merged

2022-02-28 22:20 UTC, yaron2 commented
Thanks for this @CrazyHZM!

2022-02-28 22:23 UTC, yaron2 commented
@CrazyHZM are there any documentation updates needed?

2022-03-01 02:24 UTC, CrazyHZM commented
> @CrazyHZM are there any documentation updates needed?

@yaron2 
Need to explain the use of wildcards, I will submit changes to the document later.

2022-03-08 01:43 UTC, yaron2 commented
> > @CrazyHZM are there any documentation updates needed?
> 
> @yaron2 Need to explain the use of wildcards, I will submit changes to the document later.

Ping on docs PR.

2022-03-10 06:18 UTC, CrazyHZM commented
@yaron2 
Please Review this docs PR：https://github.com/dapr/docs/pull/2249