Improve the error message
dapr/dapr pull request #4286
Opened 2022-02-23 07:57 UTC by theonefx

Signed-off-by: theonefx <chenxilzx1@gmail.com>

# Description

Improve the error message for when a state store has not been set for actor usage and actors are used

## Issue reference

Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/4273

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-02-23 11:56 UTC, mukundansundar requested changes
@theonefx check and change line 41. That is the err message which was posted in the bug that is fixed by this PR. #4273

2022-02-23 19:58 UTC, artursouza requested changes

2022-03-02 02:16 UTC, theonefx commented on pkg/messages/api_errors.go
> +	ErrStateStoresNotConfigured = "The state store is not configured to use the actor runtime. Have you set the - name: actorStateStore value: \"true\" in your state store component file?"
done

2022-04-15 01:58 UTC, daixiang0 approved these changes

2022-04-20 02:04 UTC, closed without merging

2022-04-20 02:13 UTC, yaron2 commented
@theonefx why did you close this?

2022-04-20 03:08 UTC, theonefx commented
> @theonefx why did you close this?

Sorry, this is a misoperation ....

2022-04-20 03:15 UTC, theonefx commented
@yaron2 
I resubmitted a PR there: https://github.com/dapr/dapr/pull/4533