Add feature to log Dapr API calls
dapr/dapr pull request #4288
Opened 2022-02-23 22:27 UTC by amulyavarote

# Description

Added feature to log Dapr API calls in both http and gRPC.

## Issue reference

Please reference the issue this PR will close: #4119 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-02-24 01:10 UTC, yaron2 commented
Thanks, we need to see how this affects service invocation performance (if at all).

2022-02-24 23:42 UTC, artursouza requested changes
To make the log level configurable, please use a command line argument and annotation, similar to `log-level`. For this one, we might want to call `api-log-level`. See how the command line flag and K8s annotations are all defined here: https://docs.dapr.io/reference/arguments-annotations-overview/

2022-02-24 23:42 UTC, artursouza commented on pkg/http/server.go
> +		log.Debugf("Dapr http API logging: , %s", string(ctx.Path()))
For HTTP, in addition to path, also include the HTTP Method (GET, POST, ETC).

Please, use a simpler format: "HTTP API Called: %s %s"

/cc @yaron2  @msfussell

2022-02-24 23:42 UTC, artursouza commented on pkg/grpc/server.go
> +		s.logger.Debugf("Dapr gRPC API logging: , %s", info)
Please, use "gRPC API Called: %s"

2022-02-24 23:43 UTC, artursouza commented
> Thanks, we need to see how this affects service invocation performance (if at all).

We can also have a log level "off" by default and it would not have any performance impact. This way, there is no code executed apart from the if check.

2022-02-24 23:45 UTC, artursouza requested changes

2022-02-24 23:45 UTC, artursouza commented on pkg/grpc/server.go
> +	intr = append(intr, s.getGRPCAPILogging())
If `api-log-level` is "off" or "", we don't even need to execute this line. Same for HTTP.

2022-03-01 17:35 UTC, msfussell commented
@amulyavarote - can you create a docs issue for this to track. The docs issues should contain examples on how to use this.

2022-03-04 01:54 UTC, artursouza approved these changes
Please, cut a PR in docs too.

2022-03-04 01:54 UTC, merged