Add first set of tests for APIs with resiliency
dapr/dapr pull request #4295
Opened 2022-02-25 06:45 UTC by halspang

# Description

This commit adds tests for a series of APIs that are covered by
resiliency including:

- Statestore
- Secrets
- Pubsub
- Bindings

These are generally just unit tests that show things are covered
by a policy/referencing the correct one.

Signed-off-by: Hal Spang <halspang@microsoft.com>

## Issue reference

Please reference the issue this PR will close: Resiliency

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-03-08 01:36 UTC, artursouza requested changes

2022-03-10 00:32 UTC, halspang commented on pkg/actors/actors_mock.go
> +package actors
@yaron2 - I'm not super familiar with how go packages their binaries. Is this a risk here? If it is, can I use build tags like the e2e tests? Adding something like `// build:test` to the top of the file?

2022-03-10 01:05 UTC, berndverst commented on pkg/actors/actors_mock.go
> +package actors
Yes this code would be included in the production binary.

If this package name is required build tags like `// +build unit` and then running test with `go test -v --tags=unit` seems like the way to go.

2022-03-10 01:10 UTC, berndverst approved these changes
Assuming use of build tags or moving new test code to `_test.go` files or `testing` package this looks good.

2022-03-10 17:17 UTC, halspang commented
Added a build tag @artursouza. The alternate here I guess would just be redefining the testing code inside of `actors_test.go`. I think the build tag is the more correct solution though.

2022-03-10 22:47 UTC, artursouza approved these changes

2022-03-10 22:47 UTC, merged