fix: Make sure the service is up to date every time
dapr/dapr pull request #4305
Opened 2022-02-28 12:33 UTC by alberthuang24

# Description

Keep the service up to date every time. prevent the service from remaining old when the deployment is updated

## Issue reference

fix #4287

Maybe related: https://github.com/dapr/dapr/issues/4304

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-02-28 22:11 UTC, yaron2 requested changes

2022-02-28 22:11 UTC, yaron2 commented on pkg/operator/handlers/dapr_handler.go
> +	h.patchDaprService(ctx, mayDaprService, wrapper)
Can you check for the error that's returned here?

2022-03-01 12:06 UTC, CrazyHZM requested changes

2022-03-01 12:06 UTC, CrazyHZM commented on pkg/operator/handlers/dapr_handler.go
> +		log.Errorf("unable to update service, %s, err: %s", service.Name, err)
The log is printed repeatedly, it is recommended to remove it.

2022-03-01 12:06 UTC, CrazyHZM commented
@alberthuang24 
Please fix the DCO.

2022-03-08 05:36 UTC, alberthuang24 commented
@yaron2 Is there anything else I need to do to move forward with this pr merge?

2022-03-18 22:23 UTC, yaron2 approved these changes

2022-03-21 15:58 UTC, merged

2022-03-21 15:59 UTC, yaron2 commented
Thanks for your contribution @alberthuang24