Add Sentry monitoring of certificate expiry
dapr/dapr pull request #4328
Opened 2022-03-04 18:50 UTC by berndverst

Signed-off-by: Bernd Verst <4535280+berndverst@users.noreply.github.com>

# Description

Production users of Dapr need a way to set up alerting for expiring certificates. This PR checks the certificate expiration on an hourly basis and beginning 30 days from expiry on an hourly basis emits a log entry to the Sentry warning logs indicating that the certificate will expire in X hours. Additionally an expired certificate is also logged.

Production users can setup alerting for the specific warning strings from the Sentry service logs.

2022-03-04 18:52 UTC, berndverst commented
This is the same code for determining the certificate expiration as is present in the CLI:

See https://github.com/dapr/cli/blob/master/pkg/kubernetes/mtls.go#L168
```go
	secret, err := getTrustChainSecret()
	if err != nil {
		return nil, err
	}

	caCrt := secret.Data["ca.crt"]
	block, _ := pem.Decode(caCrt)
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, err
	}
	return &cert.NotAfter, nil
```

2022-03-04 19:18 UTC, artursouza requested changes

2022-03-04 19:18 UTC, artursouza commented on pkg/sentry/sentry.go
> +				log.Warnf("Dapr root certificate expiration warning: certificate expires in %s hours", time.Until(cert.NotAfter).Hours())
Can this message be printed as "x day(s) and y hour(s)". It will improve readability IMO.

2022-03-10 05:45 UTC, berndverst commented
@yaron2 any thoughts on this? Should be pretty straightforward.

It's intended to help people set up alerting in prod for cert rotation.

2022-03-10 23:35 UTC, yaron2 approved these changes

2022-03-11 01:20 UTC, merged