fix concurrent map write
dapr/dapr pull request #4358
Opened 2022-03-12 04:24 UTC by psychomelet

fix #4353

2022-03-12 17:30 UTC, yaron2 commented
@psychomelet this looks good to me, just notice the linter failures (gofumpt and newline).

2022-03-14 02:13 UTC, daixiang0 requested changes
Please rebase main branch then we can make it land.

2022-03-14 02:14 UTC, yaron2 approved these changes

2022-03-14 02:15 UTC, merged

2022-03-14 02:16 UTC, yaron2 commented
@daixiang0 thanks, I'm able to merge this.