[WIP] Configuration restful API
dapr/dapr pull request #4562
Opened 2022-04-27 10:18 UTC by LaurenceLiZhixin

# Description

## Issue reference

Please reference the issue this PR will close: #_[issue number]_
https://github.com/dapr/dapr/issues/4528

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-04-28 20:50 UTC, yaron2 commented
@LaurenceLiZhixin please fix the linter issues: https://github.com/dapr/dapr/runs/6218476858?check_suite_focus=true.

2022-05-18 22:19 UTC, yaron2 commented
@LaurenceLiZhixin there's a failure: `undeclared name: `jsoniter` (typecheck)`.

2022-05-30 21:18 UTC, yaron2 requested changes

2022-05-30 21:18 UTC, yaron2 commented on pkg/http/api.go
> +				return errors.Errorf("Error sending binding event to application, status %d", resp.Status().Code)
Change `binding event` to `configuration item` please.

2022-05-30 21:18 UTC, yaron2 commented on pkg/http/api.go
> +			log.Error(errors.Wrap(err, "error push subscribe event to app"))
Change to `error sending configuration item to the app`.

2022-06-01 04:52 UTC, yaron2 approved these changes

2022-06-02 15:57 UTC, yaron2 commented
@LaurenceLiZhixin can you please open a PR that updates the API reference with the new endpoints? https://docs.dapr.io/reference/api/

2022-06-03 00:43 UTC, msfussell commented
@LaurenceLiZhixin - Can you also open an issue and a  PR for docs updates as well as the reference update.

These two article need to be updated, especially the code examples showing HTTP.
https://docs.dapr.io/developing-applications/building-blocks/configuration/configuration-api-overview/
https://docs.dapr.io/developing-applications/building-blocks/configuration/howto-manage-configuration/

2022-06-06 02:24 UTC, LaurenceLiZhixin commented
OK, I would do it as soon as I can.

2022-06-10 18:08 UTC, msfussell commented
Looking at the docs PR for this I would have expected this to have a key value in the URL and not in the query parameters,
to be consistent with the state management GET API. Like this?

GET  http://localhost:<daprPort>/v1.0/configuration/<storename>/<key>
example:
GET http://localhost:3500/v1.0/configuration/myConfigurationStore/myConfigKey

rather than this
GET http://localhost:3500/v1.0/configuration/myConfigurationStore?key=myConfigKey&metadata.contentType=application/json

2022-06-13 02:25 UTC, LaurenceLiZhixin commented
In the configuration get request, a key is not required. You can pass one key in a request, or multiple keys, or no keys to get the entire configuration. I think query param is more appropriate. @msfussell

2022-06-13 15:37 UTC, yaron2 commented
> 

That's correct. Thanks for the explanation.

2022-06-13 16:10 UTC, merged