components capabilities - Sidecar Metadata api changes
dapr/dapr pull request #4696
Opened 2022-06-01 13:18 UTC by pravinpushkar

Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

# Description

HTTP and gRPC API changes and Unit tests added

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-06-09 05:18 UTC, mukundansundar commented on pkg/http/api.go
> +	getComponentsToCapabilitiesFn func() map[string][]string,
```suggestion
	getComponentsCapabilitiesFn func() map[string][]string,
```
please change everywhere.

2022-06-09 07:41 UTC, mukundansundar commented
@pravinpushkar Please add docs issue link and also E2E for this API.

2022-06-21 16:40 UTC, artursouza approved these changes

2022-06-21 16:42 UTC, artursouza requested changes
Please, update the capabilities list for pubsub not to include TTL since that is a capability guaranteed by runtime.

2022-06-21 20:17 UTC, artursouza approved these changes

2022-06-21 20:18 UTC, merged