comment alicloud dubbo component to fix longhaul test data
dapr/dapr pull request #4722
Opened 2022-06-07 23:19 UTC by tanvigour

Signed-off-by: tanvigour <tanvi.gour@gmail.com>

# Description
Longhaul total cpu usage increased after this component was added. Removing this fixed the data

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-06-07 23:34 UTC, yaron2 approved these changes

2022-06-07 23:36 UTC, yaron2 commented
@tanvigour please add an issue for 1.8 to address this commenting out or work with the release team to find another suitable place to track this.

2022-06-07 23:53 UTC, tanvigour commented
> @tanvigour please add an issue for 1.8 to address this commenting out or work with the release team to find another suitable place to track this.

I have attached the issue to this: https://github.com/dapr/dapr/issues/4723 Will use it to address this

2022-06-08 00:54 UTC, artursouza requested changes

2022-06-08 00:54 UTC, artursouza commented on cmd/daprd/main.go
> +			/*bindings_loader.NewOutput("alicloud.dubbo", func() bindings.OutputBinding {
Please, just remove the component.

2022-06-09 22:57 UTC, artursouza approved these changes

2022-06-09 22:58 UTC, merged