Postgres config component2
dapr/dapr pull request #5255
Opened 2022-09-27 05:18 UTC by akhilac1

Signed-off-by: akhilac1 <chetlapalle.akhila@gmail.com>

# Description
Added postgres as a configuration store in dapr. 
Issue - #4551 
Contrib code is merged - https://github.com/dapr/components-contrib/pull/2063
docs PR has been created, review is pending - https://github.com/dapr/docs/issues/2779

Added a new file in dapr/cmd/daprd/components/configuration_postgres.go to register postgres as a supported configuration store
## Issue reference  -- #4551 

Please reference the issue this PR will close: #4551 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [ ] Created/updated tests
* [X] Unit tests passing
* [ ] End-to-end tests passing
* [X] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#https://github.com/dapr/docs/issues/2779
* [X] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs - https://github.com/dapr/docs/issues/2779
* [X] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#https://github.com/dapr/docs/issues/2779

2022-09-27 05:21 UTC, akhilac1 commented
@artursouza - created a new PR due to too many merge conflicts in #5227

2022-09-27 16:15 UTC, ItalyPaleAle requested changes

2022-09-27 16:15 UTC, ItalyPaleAle commented on go.mod
> +
Please don't change this line

2022-09-27 16:17 UTC, ItalyPaleAle commented
Need to re-run `make modtidy-all`

2022-09-28 04:05 UTC, artursouza approved these changes

2022-09-28 04:05 UTC, mukundansundar approved these changes

2022-09-28 15:29 UTC, akhilac1 commented
@artursouza - this PR is ready to be merged.

2022-09-28 17:29 UTC, ItalyPaleAle approved these changes

2022-09-29 19:14 UTC, artursouza approved these changes

2022-09-29 19:14 UTC, merged