Add addjuarez to ok-to-test
dapr/dapr pull request #5401
Opened 2022-10-21 18:58 UTC by addjuarez

Signed-off-by: Addison Juarez <adjuarez@microsoft.com>

# Description

 Give addjuarez dapr-bot permissions

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-10-21 19:27 UTC, ItalyPaleAle requested changes
#5400 is changing how this works and uses a JS file. Can you open your PR against that PR?

2022-10-24 16:26 UTC, addjuarez commented
Okay, those changes have been merged.

2022-10-24 16:56 UTC, ItalyPaleAle approved these changes

2022-10-25 01:31 UTC, artursouza approved these changes

2022-10-25 01:31 UTC, merged