config subscribe all fix for grpc
dapr/dapr pull request #5459
Opened 2022-11-04 09:30 UTC by shivamkm07

Signed-off-by: shivam <shivamkm07@gmail.com>

# Description

Fixes Subscribe to all keys not notifying changes for new keys for grpc. Fix for http was added in 1.9: https://github.com/dapr/dapr/pull/5317

## Issue reference

Please reference the issue this PR will close: #5183 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-11-04 10:06 UTC, pravinpushkar approved these changes
lgtm

2022-11-04 11:54 UTC, akhilac1 requested changes
Please add a test case for empty keys to api_test.go

2022-11-04 19:48 UTC, ItalyPaleAle submitted a review, later dismissed

2022-11-10 18:53 UTC, DeepanshuA commented
> Please add a test case for empty keys to api_test.go

Agreed, this test will add value - probably in a 2 phased way, where-in in between new rows are added.

2022-11-10 18:54 UTC, DeepanshuA commented
@shivamkm07 Please check, some UTs seem to be failing: https://github.com/dapr/dapr/actions/runs/3435204062/jobs/5727303021

2022-11-26 18:36 UTC, ItalyPaleAle approved these changes

2022-11-26 18:41 UTC, merged