Fixes linter issues, upgrades linter
dapr/dapr pull request #5503
Opened 2022-11-11 21:02 UTC by berndverst

- upgrade to golangci-lint 1.50.1,
- fix linter issues,
- disable deprecated linters

Signed-off-by: Bernd Verst <4535280+berndverst@users.noreply.github.com>

2022-11-11 21:09 UTC, ItalyPaleAle requested changes
Can you please update the linter version in a few more places:

- Docs such as these here: https://github.com/dapr/dapr/tree/master/docs/development
- The dev container file

2022-11-11 21:29 UTC, berndverst commented on .golangci.yml
> +    - ^pkg.proto.*
Didn't mean to commit this -- let me remove here.

```suggestion
```

2022-11-11 21:39 UTC, ItalyPaleAle submitted a review, later dismissed

2022-11-12 01:22 UTC, mukundansundar approved these changes

2022-11-14 01:14 UTC, daixiang0 approved these changes
LGTM

2022-11-14 01:23 UTC, daixiang0 commented
Please fix CI, as
https://github.com/dapr/dapr/actions/runs/3448087615/jobs/5771538556#step:15:155

2022-11-15 03:04 UTC, daixiang0 approved these changes

2022-11-15 03:04 UTC, merged