Hotfix 1.9.5 and release notes
dapr/dapr pull request #5588
Opened 2022-11-30 20:57 UTC by RyanLettieri

Signed-off-by: Ryan Lettieri <ryanLettieri@microsoft.com>

# Description

Release hotfix for 1.9.5 which covers the fix for cosmosDB etag crash, 
Release hotfix for 1.9.5 which covers the fix for init failure due to kubernetes built in secret store being disabled

## Issue reference

See [#5576 ](https://github.com/dapr/dapr/issues/5576)

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-11-30 21:05 UTC, ItalyPaleAle requested changes

2022-11-30 21:05 UTC, ItalyPaleAle commented on docs/release_notes/v1.9.5.md
> +This issue impacts all users of CosmosDB state store.
```suggestion
This issue impacts all users of the Azure Cosmos DB state store on Dapr 1.9.0-1.9.4.
```

2022-11-30 21:05 UTC, ItalyPaleAle commented on docs/release_notes/v1.9.5.md
> +When setting any ETag in a transaction request inside CosmosDB, dapr exits due to a nil pointer dereference.
```suggestion
When setting any ETag in a transaction request with the Azure Cosmos DB state store, Dapr panics with a nil pointer dereference.
```

2022-11-30 21:05 UTC, ItalyPaleAle commented on docs/release_notes/v1.9.5.md
> +When setting an ETag on a transaction request in CosmosDB state store, a nil pointer was being dereferenced.
```suggestion
When setting an ETag on a transaction request in the Azure Cosmos DB state store, a bug causes Dapr to panic.
```

2022-11-30 21:05 UTC, ItalyPaleAle commented on docs/release_notes/v1.9.5.md
> +We fixed a bug that caused Dapr to panic
```suggestion
We fixed a bug that caused Dapr to panic.
```

2022-11-30 21:06 UTC, ItalyPaleAle requested changes
Backported by review comments from the other PR

2022-11-30 21:06 UTC, ItalyPaleAle commented on docs/release_notes/v1.9.5.md
> +## Fixes an issue in the CosmosDB state store component when performing transaction request with ETags
```suggestion
## Fixes a panic in the Azure Cosmos DB state store component when performing transaction request with ETags
```

2022-11-30 21:06 UTC, ItalyPaleAle commented on docs/release_notes/v1.9.5.md
> +- Fixes an issue in the CosmosDB state store component when performing transaction request with ETags
```suggestion
- Fixes a panic in the Azure Cosmos DB state store component when performing transaction request with ETags
```

2022-11-30 22:25 UTC, ItalyPaleAle requested changes

2022-11-30 22:25 UTC, ItalyPaleAle commented on docs/release_notes/v1.9.5.md
> +After closing the client stream in the actor placement service, the stream was being set to nil.
```suggestion
We identified a race condition in the actor placement service client that could have caused the Dapr to panic after recovering from a failure.
```

2022-11-30 22:25 UTC, ItalyPaleAle commented on docs/release_notes/v1.9.5.md
> +We updated actor placement service to properly close the client stream and no longer set it to nil.
```suggestion
We updated actor placement service to address the race condition and remove the cause for the panic.
```

2022-12-01 00:02 UTC, ItalyPaleAle requested changes

2022-12-01 00:02 UTC, ItalyPaleAle commented on docs/release_notes/v1.9.5.md
> +Retained mqtt messages should be only processed once, however, they were not being acknowledged and thus were resent indefinitely.
MQTT uppercase

2022-12-01 00:02 UTC, ItalyPaleAle commented on docs/release_notes/v1.9.5.md
> +This issue impacts all users of MQTT on Dapr 1.9.0-1.9.4.
```suggestion
This issue impacts all users of the MQTT PubSub component on Dapr 1.9.0-1.9.4, who have enabled `retain` in the component's metadata.
```

2022-12-01 00:02 UTC, ItalyPaleAle commented on docs/release_notes/v1.9.5.md
> +We updated Dapr to acknowledge a retained message.
```suggestion
We updated Dapr to acknowledge a retained message in the MQTT PubSub component.
```

2022-12-01 00:30 UTC, yaron2 approved these changes

2022-12-01 00:30 UTC, yaron2 commented
/ok-to-test

2022-12-01 03:15 UTC, DeepanshuA commented on docs/release_notes/v1.9.5.md
> +This issue impacts all users of the MQTT PubSub component on Dapr 1.9.0-1.9.4, who have enabled `retain` in the component's metadata.
```suggestion
This issue impacts all users of the MQTT PubSub component on Dapr 1.9.0-1.9.4, where-in a subscriber using MQTT component receives a `retained` message.
```

2022-12-01 16:12 UTC, yaron2 approved these changes

2022-12-01 16:12 UTC, merged