Workflow proto changes and test hardening
dapr/dapr pull request #5833
Opened 2023-01-27 17:19 UTC by RyanLettieri

Signed-off-by: Ryan Lettieri <ryanLettieri@microsoft.com>

# Description

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-01-27 17:23 UTC, artursouza requested changes

2023-01-27 17:23 UTC, artursouza commented on tests/apps/workflowsapp/app.go
> +	for i := 0; i < 5; i++ {
Why 5? If just the number of workers, then it should be a const.

2023-01-27 17:23 UTC, artursouza commented on tests/dapr_tests.mk
> +					--set temporalio/server=1.15.1 \
How will the test know to pull from GH and not from DockerHub?

2023-03-21 22:14 UTC, ItalyPaleAle commented
Since this test has been deleted, this PR should probably be closed?

2023-03-21 22:18 UTC, RyanLettieri commented
@ItalyPaleAle Yeah we can close this PR

2023-03-21 22:18 UTC, closed without merging