feat: Healthz api check appId support
dapr/dapr pull request #5868
Opened 2023-02-01 09:19 UTC by alberthuang24

related: https://github.com/dapr/components-contrib/issues/2489

Signed-off-by: AlbertHuang <r.albert.huang@gmail.com>

# Description

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-02-01 15:31 UTC, ItalyPaleAle commented
CC: @DeepanshuA since you've been looking into the healthz API

2023-02-15 14:03 UTC, DeepanshuA commented
@alberthuang24 I am not able to understand the use-case behind this work.
When I was working on components Health check API work, then it was discussed and realized that we may want rather different query params in future with existing healthz check api itself.
Can you please raise an issue and elaborate that how does having {appid} in url helps, and for what use-cases. I think there-in it may be concluded the best approach forward, and then a PR can follow.

2023-02-20 01:05 UTC, alberthuang24 commented
Hello @DeepanshuA 

This support was added to allow external parties to pass the expected `app-id`. 
This method allows external applications to determine if some old IP address is still the expected `app-id`

This prevents the `consul name-resolution component` from incorrectly resolving the service to another `app-id` IP address as mentioned in https://github.com/dapr/components-contrib/issues/2489

2023-02-20 01:09 UTC, alberthuang24 commented
Maybe we could also add a separate entry for the checksum. Perhaps called `healthz/expect/{app-id}`

2023-02-20 01:55 UTC, ItalyPaleAle commented
hi @alberthuang24 would the solution implemented in #5914, which will ship with Dapr 1.11, work for your scenario?

2023-02-22 10:11 UTC, alberthuang24 commented
> hi @alberthuang24 would the solution implemented in #5914, which will ship with Dapr 1.11, work for your scenario?

This #5914 only addresses local issues, I need to use `consul-dns` on kubernetes

2023-02-23 22:01 UTC, ItalyPaleAle commented
As discussed in https://github.com/dapr/components-contrib/pull/2490, the intent of this PR can be better addressed in a different way, as per https://github.com/dapr/components-contrib/pull/2594

2023-03-10 10:26 UTC, alberthuang24 commented
@ItalyPaleAle Is There an updated conclusion?

2023-03-13 17:05 UTC, artursouza requested changes

2023-03-13 17:05 UTC, artursouza commented on pkg/http/api.go
> +			Route:         "healthz/{appId:*}",
Can we use query param instead?

2023-03-13 17:39 UTC, ItalyPaleAle commented
> Is There an updated conclusion?

@alberthuang24 We spoke about this during the maintainers call this morning. I'm ok with this approach and so is @artursouza .

However, Artur asked (see his review) if we can pass this as query string argument rather than URL path, since it can allow more flexibility in the future.

2023-04-04 02:46 UTC, alberthuang24 commented
> > Is There an updated conclusion?
> 
> @alberthuang24 We spoke about this during the maintainers call this morning. I'm ok with this approach and so is @artursouza .
> 
> However, Artur asked (see his review) if we can pass this as query string argument rather than URL path, since it can allow more flexibility in the future.

done.

2023-04-04 16:47 UTC, ItalyPaleAle commented
@alberthuang24

I wasn't able to make changes into your branch (you didn't turn on "allow maintainers to make changes"), so please do this:

```sh
git pull https://github.com/italyPaleAle/dapr update-5868
```

Among other things, this changes the query string parameter to `appid` (we don't normally put dashes in it, such as `app-id`).

Then I'll approve

2023-04-06 05:04 UTC, alberthuang24 commented
> @alberthuang24
> 
> I wasn't able to make changes into your branch (you didn't turn on "allow maintainers to make changes"), so please do this:
> 
> ```shell
> git pull https://github.com/italyPaleAle/dapr update-5868
> ```
> 
> Among other things, this changes the query string parameter to `appid` (we don't normally put dashes in it, such as `app-id`).
> 
> Then I'll approve

done

2023-04-06 05:06 UTC, ItalyPaleAle submitted a review, later dismissed

2023-04-06 16:43 UTC, ItalyPaleAle approved these changes

2023-04-07 02:29 UTC, daixiang0 reviewed
Please update the base, thanks.

2023-04-07 03:56 UTC, alberthuang24 commented
done.

2023-04-11 16:24 UTC, ItalyPaleAle commented
@alberthuang24 please enable this checkmark:

![image](https://user-images.githubusercontent.com/43508/231227272-8cd68c76-3918-408d-a8b7-39089f1c66e1.png)

This way we can ensure the branch is up-to-date and merge it

2023-04-12 04:02 UTC, ItalyPaleAle commented
It would be here, under the participants:

![image](https://user-images.githubusercontent.com/43508/231346160-a21ab072-533d-43e5-9034-f0a098255e75.png)

Maybe it's because you've opened this PR from your master branch?

We could either:

- Close this PR and re-open it from a different branch
- Re-open this PR for you (giving you credit in the commits)

2023-04-17 08:00 UTC, mukundansundar commented
> It would be here, under the participants:
> 
> ![image](https://user-images.githubusercontent.com/43508/231346160-a21ab072-533d-43e5-9034-f0a098255e75.png)
> 
> Maybe it's because you've opened this PR from your master branch?
> 
> We could either:
> 
> * Close this PR and re-open it from a different branch
> * Re-open this PR for you (giving you credit in the commits)

@alberthuang24 Can you reopen this PR after updating the latest changes from master? 
Please do give permissions to maintainers to update the PR

2023-04-23 12:54 UTC, closed without merging