Issue 5778
dapr/dapr pull request #5901
Opened 2023-02-07 18:03 UTC by cmoulliard

# Description

Add a new ingress template to the dashboard helm chart

## Issue reference

Issue 5778

Please reference the issue this PR will close: #_5778_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

## End to end test

Here is what I did locally to test it

```
- Created a local kind k8s cluster where nginx ingress controller is deployed
- Create a dapr.yml file containing the following values
  dapr_dashboard:
    runAsNonRoot: true
    ingress:
      enabled: true
      className: nginx
      host: dapr.127.0.0.1.nip.io
- helm install dapr -n dapr --create-namespace -f dapr.yml ../dapr-fork/charts/dapr
- Controled successfully if a ingress resource has been created
k get ingress -A
NAMESPACE   NAME             CLASS   HOSTS                   ADDRESS         PORTS   AGE
dapr        dapr-dashboard   nginx   dapr.127.0.0.1.nip.io   10.96.105.166   80      23m
- Accessed the dashboard url from my browser
```
![Screenshot 2023-02-07 at 19 02 14](https://user-images.githubusercontent.com/463790/217328509-f7b944ff-9659-4405-b7c7-e0d47dda4cd3.png)

2023-02-07 18:13 UTC, ItalyPaleAle submitted a review, later dismissed
A few changes to the wording of the docs, otherwise LGTM, thanks!

2023-02-07 18:13 UTC, ItalyPaleAle commented on charts/dapr/README.md
> +| `dapr_dashboard.ingress.host`           | Fully qualified hostname of the dashboard URL (e.g dapr.127.0.0.1.nip.io)
```suggestion
| `dapr_dashboard.ingress.host`           | Fully qualified hostname of the dashboard URL (e.g `dashboard.dapr.local`) | ``  |
```

2023-02-07 18:13 UTC, ItalyPaleAle commented on charts/dapr/README.md
> +| `dapr_dashboard.ingress.tls.enabled`    | Boolean value for enabling the HTTPS/TLS endpoint
```suggestion
| `dapr_dashboard.ingress.tls.enabled`    | If true, enables TLS on the ingress for the Dashboard                                                                                                                      | `false`            |
```

2023-02-07 18:13 UTC, ItalyPaleAle commented on charts/dapr/README.md
> +| `dapr_dashboard.ingress.tls.secretName` | Secret name of the kubernetes tls secret (key/certificate)
```suggestion
| `dapr_dashboard.ingress.tls.secretName` | Name of the Kubernetes secret containing the TLS certificate (key/certificate) for the Dashboard. Ignored if `dapr_dashboard.ingress.tls.enabled` is `false`. | ``                 |
```

2023-02-07 18:14 UTC, ItalyPaleAle commented
Also please fix the DCO issue: https://docs.dapr.io/contributing/contributing-overview/#every-commit-needs-to-be-signed

2023-02-07 18:28 UTC, berndverst commented
Might as well update the default dashboard image tag here to 0.11.1 also (which we are about to release)

2023-02-08 00:12 UTC, yaron2 requested changes

2023-02-08 00:12 UTC, yaron2 commented on charts/dapr/README.md
> +| `dapr_dashboard.image.tag`              | docker image tag
Change default to `0.11.1`.

2023-02-08 10:07 UTC, cmoulliard commented on charts/dapr/README.md
> +| `dapr_dashboard.image.tag`              | docker image tag
Fixed with last commit 346b99d

2023-02-08 10:10 UTC, salaboy commented
awesome stuff! @cmoulliard , still DCO is complaining and is rebase needed?

2023-02-08 15:29 UTC, yaron2 approved these changes

2023-02-08 15:30 UTC, merged

2023-02-08 16:05 UTC, yaron2 commented
Thanks for your contribution @cmoulliard