Reconcile dapr service for argo rollout
dapr/dapr pull request #6052
Opened 2023-03-09 12:38 UTC by sunzhaochang

# Description

Support service reconciler for dapr-enabled argo rollouts.

## Issue reference

Please reference the issue this PR will close: #6034 and #5605 

## Test case
1. Install dapr with `argoRolloutServiceReconciler.enabled` option:
```
helm install --set global.argoRolloutServiceReconciler.enabled=true -f charts/dapr/values.yaml mydapr ./charts/dapr/
```
2. Create dapr-enabled argo rollout resource:
```
cat <<EOF | kubectl apply -f -
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: dapr-test
spec:
  replicas: 5
  revisionHistoryLimit: 2
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "rollouts-demo"
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
EOF
```
Then the dapr service will be created by operator:
```
$ kubectl get svc -n dapr-test
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                               AGE
rollouts-demo-dapr   ClusterIP   None         <none>        80/TCP,50001/TCP,50002/TCP,9090/TCP   70s
```
3. Delete the argo rollout resource and dapr service will also be deleted:
```
$ kubectl delete -n dapr-test rollouts.argoproj.io rollouts-demo 
rollout.argoproj.io "rollouts-demo" deleted
$ kubectl get svc -n dapr-test
No resources found in dapr-test namespace.
```
## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-03-09 16:28 UTC, ItalyPaleAle requested changes
I am not familiar with Argo Rollout so I can only review the code itself, but LGTM with just 2 minor changes please

2023-03-09 16:28 UTC, ItalyPaleAle commented on charts/dapr/values.yaml
> +  argoRolloutServiceReconciler:
Please update https://github.com/dapr/dapr/blob/master/charts/dapr/README.md too

2023-03-09 16:28 UTC, ItalyPaleAle commented on cmd/operator/main.go
> +	flag.BoolVar(&enableArgoRolloutServiceReconciler, "enable-argo-rollout-service-reconciler", false, "Enable the service reconciler for dapr-enabled Argo Rollouts")
```suggestion
	flag.BoolVar(&enableArgoRolloutServiceReconciler, "enable-argo-rollout-service-reconciler", false, "Enable the service reconciler for Dapr-enabled Argo Rollouts")
```

2023-03-09 16:51 UTC, sunzhaochang commented on charts/dapr/values.yaml
> +  argoRolloutServiceReconciler:
Done

2023-03-09 18:00 UTC, ItalyPaleAle submitted a review, later dismissed

2023-03-09 21:58 UTC, ItalyPaleAle commented
/ok-to-test

2023-03-14 15:59 UTC, yaron2 requested changes

2023-03-15 02:49 UTC, sunzhaochang commented on pkg/operator/handlers/dapr_handler.go
> +func NewDaprHandler(mgr ctrl.Manager, argoRolloutServiceReconcilerEnabled bool) *DaprHandler {
I replaced the single param with options struct. Please take a look.

2023-03-15 03:10 UTC, yaron2 approved these changes

2023-03-15 03:55 UTC, merged