Fix create reminder for HTTP API.
dapr/dapr pull request #6295
Opened 2023-04-28 15:35 UTC by artursouza

# Description

Fix (regression) to create reminder for HTTP API.

## Issue reference

Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/6268

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-04-28 16:16 UTC, yaron2 requested changes

2023-04-28 16:16 UTC, yaron2 commented on pkg/sentry/ca/issuer.key
> +-----BEGIN EC PRIVATE KEY-----
Remove this, probably a leftover from `make test`.

2023-04-28 16:40 UTC, berndverst submitted a review, later dismissed
Remove the certificate file as @yaron2 mentioned please. Looks good otherwise though.

This change makes the Python SDK actor test succeed.

2023-04-28 16:42 UTC, berndverst commented
Unit tests for Actor Reminders and E2E tests are now failing @artursouza

2023-04-28 16:55 UTC, artursouza commented
> Unit tests for Actor Reminders and E2E tests are now failing @artursouza

Will fix.

2023-04-28 17:01 UTC, berndverst commented
At a high level what we need here is this:

1. Check whether data is base64 encoded. Try base64 decoding the data to verify.
2. If that fails assume the data is is already decoded.
3. With the decoded string - now assume it's JSON. Try unmarshalling the JSON.
4. If that fails, assume the string is plain text -- create a JSON envelope and add the string to it. Include a property to indicate the value is supposed to be returned as plain text.
5. Now store the new reminder data in the DB.

When retrieving reminder data you need to then check for the presence / value of this plain text property in the envelope to determine whether to return a plaintext string or a JSON string.

2023-05-02 03:24 UTC, artursouza commented
Converting this to draft. Needs further investigation as fixing one regression creates another - just like we have been observing with the sequence of patch releases in 1.10. As I worked on fixing a regression on reminders, I have also identified one in timers. Both should be addressed in this PR but I have not found a fix yet that does not cause a regression in other parts of the system.

2023-05-02 23:43 UTC, berndverst commented
The current fix is still problematic.

Python actor test does not pass. Produces a new error signature:

```
"PUT /actors/DemoActor/1/method/remind/demo_reminder HTTP/1.1" 500 Internal Server Error
		time="2023-05-02T16:40:18.003475-07:00" level=error msg="Error executing reminder for actor DemoActor||1||demo_reminder: error from actor service: {\"message\":\"JSONDecodeError('Expecting value: line 1 column 1 (char 0)')\",\"errorCode\":\"UNKNOWN\"}" app_id=demo-actor instance=Bernds-MBP.localdomain scope=dapr.runtime.actor type=log ver=edge
```

2023-05-03 00:13 UTC, artursouza commented
> The current fix is still problematic.
> 
> Python actor test does not pass. Produces a new error signature:
> 
> > == APP == INFO:     127.0.0.1:50016 - "PUT /actors/DemoActor/1/method/remind/demo_reminder HTTP/1.1" 500 Internal Server Error
> > time="2023-05-02T16:40:18.003475-07:00" level=error msg="Error executing reminder for actor DemoActor||1||demo_reminder: error from actor service: {"message":"JSONDecodeError('Expecting value: line 1 column 1 (char 0)')","errorCode":"UNKNOWN"}" app_id=demo-actor instance=Bernds-MBP.localdomain scope=dapr.runtime.actor type=log ver=edge
> > time="2023-05-02T16:40:18.003518-07:00" level=error msg="Error while executing reminder DemoActor||1||demo_reminder: error from actor service: {"message":"JSONDecodeError('Expecting value: line 1 column 1 (char 0)')","errorCode":"UNKNOWN"}" app_id=demo-actor instance=Bernds-MBP.localdomain scope=dapr.runtime.actor type=log ver=edge

Let me ping you on this to understand the scenario. The one I had passes.

2023-05-03 00:28 UTC, berndverst commented
> > The current fix is still problematic.
> > Python actor test does not pass. Produces a new error signature:
> > > == APP == INFO:     127.0.0.1:50016 - "PUT /actors/DemoActor/1/method/remind/demo_reminder HTTP/1.1" 500 Internal Server Error
> > > time="2023-05-02T16:40:18.003475-07:00" level=error msg="Error executing reminder for actor DemoActor||1||demo_reminder: error from actor service: {"message":"JSONDecodeError('Expecting value: line 1 column 1 (char 0)')","errorCode":"UNKNOWN"}" app_id=demo-actor instance=Bernds-MBP.localdomain scope=dapr.runtime.actor type=log ver=edge
> > > time="2023-05-02T16:40:18.003518-07:00" level=error msg="Error while executing reminder DemoActor||1||demo_reminder: error from actor service: {"message":"JSONDecodeError('Expecting value: line 1 column 1 (char 0)')","errorCode":"UNKNOWN"}" app_id=demo-actor instance=Bernds-MBP.localdomain scope=dapr.runtime.actor type=log ver=edge
> 
> Let me ping you on this to understand the scenario. The one I had passes.

Somehow didn't have all your commits checked out. I updated my local copy of your branch the forceful way and built again.. then it worked!

2023-05-03 05:21 UTC, mukundansundar commented
@artursouza this latest commit is failing against example validation in Java SDK and Go-sdk ... Ran it a couple of times locally after building daprd from this commit. 
@DeepanshuA also ran the go-sdk actor validation steps to confirm.

2023-05-03 22:20 UTC, artursouza commented
I also validated the Python SDK example with a small variation:
Run actor with runtime v1.10.4, register reminder with longer TTL, stop runtime, start again with this patched version - reminders continue to fire after restart, as expected.

2023-05-03 22:50 UTC, yaron2 approved these changes

2023-05-04 00:56 UTC, merged

2023-05-04 06:46 UTC, ItalyPaleAle commented
@artursouza looks like this modifies the format of the data stored in the database which is now marshaled as JSON. have you confirmed this is backwards and forward compatible too? I used to run tests by creating a reminder on 1.10.4, upgrading and verifying the data came back correctly, and then doing the opposite (create with newer and verify it fires on older)