Adds scheduled, and manual test runner, for the Dapr Java SDK test validation.
dapr/dapr pull request #6304
Opened 2023-05-03 14:24 UTC by JoshVanL

Part of #5797.

Adds GitHub action workflow for running SDK tests against Dapr HEAD. These are run on an infrequent schedule, as well as on pull requests when someone comments `/test-sdk-all`.

Currently only tests  the Java SDK, which can also be triggered with `/test-sdk-java`.

Not fully tested e2e just because of how GH actions work, but hopefully should be close to working.

/cc @artursouza

2023-05-03 16:17 UTC, JoshVanL commented
/test-sdk-java

2023-05-03 16:59 UTC, artursouza reviewed
Can you push this to your fork's master and paste the link of the run over there?

2023-05-03 16:59 UTC, artursouza commented on .github/workflows/dapr-test-sdk.yml
> +  DAPR_CLI_VER: 1.10.0
Can you install the latest Dapr CLI?

2023-05-03 16:59 UTC, artursouza commented on .github/workflows/dapr-test-sdk.yml
> +      matrix:
Please, pick only one variation. This will save in the total number of runs in parallel.

2023-05-03 16:59 UTC, artursouza commented on .github/workflows/dapr-test-sdk.yml
> +    - name: Codecov
We can remove code coverage.

2023-05-03 22:48 UTC, berndverst commented
If you want I can push a commit to this to add Python validation also.

2023-05-04 00:03 UTC, berndverst commented
I took the liberty to push a Python workflow to your PR and fix an issue in your PR.

I reduced the Java runs - but I don't know which versions you want, please update accordingly!

Also I noticed that the `/test-sdk-python` for example still triggers the java run too, so that logic seems incorrect there.

2023-05-04 10:06 UTC, JoshVanL commented
Thanks @berndverst. Personally I prefer to have only review comments on my PRs, or a PR to my branch, rather than pushing straight to it. Do make sure to update the PR description too! it's really no worries though, thank you for the work :slightly_smiling_face:

2023-05-04 11:15 UTC, JoshVanL commented
Thanks both! I have addressed the comments and fixed the issues. Jobs are now properly run using the commands as expected.

You can see these jobs being triggered in my personal fork (note, I believe these failures are true positives):
- https://github.com/JoshVanL/dapr/actions/runs/4882054149
- https://github.com/JoshVanL/dapr/actions/runs/4881969948
- https://github.com/JoshVanL/dapr/actions/runs/4881880280

2023-05-04 17:37 UTC, berndverst commented
> Thanks @berndverst. Personally I prefer to have only review comments on my PRs, or a PR to my branch, rather than pushing straight to it. Do make sure to update the PR description too! it's really no worries though, thank you for the work 🙂

Absolutely, and I wouldn't usually do that, so definitely feel free to remove my commits.

Given all the issues we have seen in gRPC based actor SDKs and HTTP based actor SDKs - it seemed critical to also enable a HTTP based SDK validation immediately to help with our release testing. In this case I figured it is better to ask for forgiveness. So my apologies!
Having multiple PRs open unnecessarily for essentially duplicate things just causes a significant delay - reviewers don't get to them, and as a PR author you of course need to deal with the conflicts. And then there is the GitHub runner resource shortage too...

Rather than leaving a review comment saying "Also add the Python SDK here" and pointing you to the steps, was trying to simplify that for you. At this stage it is best to reduce the number of PRs.

Won't update anyone's PR in runtime again! Sorry :)

2023-05-04 19:28 UTC, mukundansundar submitted a review, later dismissed

2023-05-04 19:28 UTC, mukundansundar commented on .github/workflows/dapr-test-sdk.yml
> +      JDK_VER: 16
```suggestion
      JDK_VER: 11
```
please use 11 ... 16 is not LTS

2023-05-04 19:35 UTC, mukundansundar commented on .github/workflows/dapr-test-sdk.yml
> +        run: cd java-sdk && mvn -B test -q
this step can be removed.

2023-05-09 16:52 UTC, mukundansundar requested changes
Please add `/test-sdk-all` and the other ones to the https://github.com/dapr/dapr/blob/master/.github/scripts/dapr_bot.js

2023-05-09 22:21 UTC, mukundansundar approved these changes

2023-05-16 05:19 UTC, artursouza commented
Why does the Python SDK fail (1) and why does it show a green check when it fails (2)?

2023-05-16 14:42 UTC, artursouza approved these changes

2023-05-16 14:42 UTC, merged