Add constant for activityId delimiter
dapr/dapr pull request #6314
Opened 2023-05-05 07:51 UTC by DeepanshuA

# Description

It simply adds a constant for Activity Id Deliemiter (`::`).

## Issue reference

Please reference the issue this PR will close: #6313 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-05-05 07:55 UTC, shubham1172 approved these changes

2023-05-05 09:16 UTC, shubham1172 approved these changes

2023-05-05 13:23 UTC, JoshVanL requested changes

2023-05-05 13:23 UTC, JoshVanL commented on utils/utils.go
> +	WFActivityIDDelimiter = "::" // Delimiter between workflow id and activity id
I think this const would be better to live in `pkg/runtime/wfengine`, or ideally, in `pkg/runtime/consts` (I am currently in the process of breaking up `runtime.go` where I have also created this package).

2023-05-29 01:17 UTC, daixiang0 commented
@DeepanshuA could you update it?

2023-06-20 05:53 UTC, mukundansundar commented
@DeepanshuA please fix the conflicts and review comments.

2023-10-20 09:28 UTC, mukundansundar commented
@DeepanshuA Please fix conflicts in the PR and address review comments.

2024-02-24 09:51 UTC, closed without merging