State store: make BulkSet/BulkDelete not transactional
dapr/dapr pull request #6342
Opened 2023-05-12 20:34 UTC by ItalyPaleAle

**Needs dapr/components-contrib#2834 to be merged first**

This is a follow-up from #6186 that addresses the requested change of making BulkSet/BulkDelete operations in state stores not use transactions, and instead revert to perform operations one-by-one.

It is needed also to make sure that the correct HTTP status codes are returned to users when state operations fail with etag errors in bulk operations, per: https://github.com/dapr/dapr/pull/6186#issuecomment-1539262923 (which is currently a P0 blocker  for #6301 )

The main concern behind changing to using transactions in #6186 was that the previous way of running bulk operations did not play well with resiliency. For example, assume that the user wanted to set 3 keys: A, B, and C; all of them have an etag. Previously, operations were executed in sequence and errors would have caused to abort the sequence. If, for example, B failed with an etag error and resiliency was enabled, Dapr would have retried all operations, including A which would have now failed with an etag failure (because A was updated).

This PR changes how the bulk operations are performed:

1. Operations are now performed in parallel and not in sequence. There is support for limiting concurrency, although that's not exposed to end users right now as it requires changes to user-facing APIs which I thought not appropriate this late in the endgame. However, exposing this should be relatively easy.
2. When an operation fails, resiliency will retry only failed operations that are retriable. Operations that fail because of an etag error are not retried.

It fixes the error reported in https://github.com/dapr/dapr/pull/6186#issuecomment-1539262923 so the correct status codes are returned. New (unit) tests have been added to make sure that status codes will not change again, even for bulk operations, for both HTTP and GRPC.

Changes are to both bulk set and bulk delete operations.

## Future plans

There are a few things that are not included in this PR which could (should?) be done in the future:

- When a bulk set/delete operation fails, we should probably return details on what operation failed specifically. Right now we just return an internal error if at least one operation failed with any error that's not an etag error. Otherwise, we return a conflict error if at least one operation failed with an etag error. However, users have no way to know which operation failed.
- It also occurred to me that Dapr doesn't implement a Bulk Delete API in HTTP. It does exist in GRPC, but not in HTTP.
- As mentioned, bulk set operations at the moment are all executed in parallel. The internal APIs have an option to limit concurrency, but that's not exposed to end users at the moment.

2023-05-12 21:09 UTC, artursouza reviewed
Please, add an E2E test to reproduce the original issue.

2023-05-16 18:49 UTC, ItalyPaleAle commented
Added E2E tests (had to be created _ex-novo_ because there were no E2E tests for state store etags). PR should be ready.

Contrib PR will need to be merged before this however.

2023-05-16 18:51 UTC, ItalyPaleAle commented
/ok-to-test

2023-05-16 19:21 UTC, ItalyPaleAle commented
/ok-to-test

2023-05-16 19:27 UTC, berndverst commented
/ok-to-test

2023-05-16 19:30 UTC, ItalyPaleAle commented on go.mod
> +replace github.com/dapr/components-contrib => github.com/dapr/components-contrib v1.11.0-rc.2.0.20230516184520-41303a9b0c00
Leaving this comment to remember to remove this

2023-05-17 00:41 UTC, ItalyPaleAle commented
/ok-to-test

2023-05-17 22:49 UTC, ItalyPaleAle commented
/ok-to-test

2023-05-18 00:19 UTC, ItalyPaleAle commented
/ok-to-test

2023-05-18 01:02 UTC, berndverst commented
Sorry I pushed a bad contrib tag. I will repush as rc4 and update this PR

2023-05-18 01:07 UTC, berndverst commented
/ok-to-test

2023-05-18 15:20 UTC, artursouza requested changes

2023-05-18 16:06 UTC, ItalyPaleAle commented
/ok-to-test

2023-05-18 16:09 UTC, artursouza commented
/ok-to-test

2023-05-18 16:09 UTC, artursouza commented
/ok-to-test

2023-05-18 16:10 UTC, artursouza commented
/test-sdk-all

2023-05-18 16:11 UTC, artursouza commented
/ok-to-perf

2023-05-18 16:53 UTC, ItalyPaleAle commented
/ok-to-test

2023-05-18 16:53 UTC, ItalyPaleAle commented
/ok-to-perf

2023-05-18 16:53 UTC, ItalyPaleAle commented
/test-sdk-all

2023-05-18 16:53 UTC, ItalyPaleAle commented on .github/workflows/dapr-test-sdk.yml
> +      - name: Check out code
The SDK tests were failing because it was cloning master rather than the PR. This should fix it.

2023-05-18 16:54 UTC, ItalyPaleAle commented on .github/workflows/dapr-test-sdk.yml
> +          header: ${{ github.run_id }}-python
This allows having a separate comment for python and java, so updates should work now (hopefully)

2023-05-18 16:54 UTC, ItalyPaleAle commented on .github/workflows/dapr-test-sdk.yml
> +    - cron: "16 */11 * * 1-5"
Changed to not be on top of the hour because that's when Actions is busier :)

2023-05-18 16:59 UTC, ItalyPaleAle commented
SDK tests are still expected to fail until the updated workflows are merged into master.

I have confirmed the Python SDK examples pass on my machine against this PR.

2023-05-18 22:41 UTC, artursouza commented
/ok-to-test

2023-05-18 22:41 UTC, artursouza commented
/test-sdk-all

2023-05-18 23:30 UTC, ItalyPaleAle commented
/ok-to-test

2023-05-18 23:37 UTC, artursouza approved these changes

2023-05-18 23:37 UTC, merged