Passing gRPC max msg size to proxy client stream
dapr/dapr pull request #6353
Opened 2023-05-16 00:21 UTC by Flern

# Description

Updated the `handler.go` file to use a passed-in argument of `maxMessageBodySizeMB` that is provided from the `runtime.go` instantiation of the proxy down through the `TransparentHandler` by using the configuration item `--dapr-http-max-request-size` parameter.  If there is no parameter configured, a zero value is propagated, so any value of zero (or less) is ignored and defaults are used.

## Issue reference

https://github.com/dapr/dapr/issues/6349

Please reference the issue this PR will close: #_6349_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-05-16 02:28 UTC, ItalyPaleAle commented
Overall I think this is fine. 2 comments:

1. Using `dapr-http-max-request-size` doesn't feel right for something that is related to gRPC. Should we have a separate CLI flag for this maybe? Also, whatever flag should also apply to our gRPC server too perhaps (not just for gRPC proxying).
2. Could you please update one of the E2E tests, such as the gRPC proxying one, to validate that with this flag we can send messages larger than 4MB?

2023-05-16 02:38 UTC, yaron2 commented
> 1. Using `dapr-http-max-request-size` doesn't feel right for something that is related to gRPC. Should we have a separate CLI flag for this maybe? Also, whatever flag should also apply to our gRPC server too perhaps (not just for gRPC proxying).

We should reuse `dapr-http-max-request-size` here as this is already applied to our gRPC servers.

2023-05-16 02:41 UTC, ItalyPaleAle commented
> > 1. Using `dapr-http-max-request-size` doesn't feel right for something that is related to gRPC. Should we have a separate CLI flag for this maybe? Also, whatever flag should also apply to our gRPC server too perhaps (not just for gRPC proxying).
> 
> We should reuse `dapr-http-max-request-size` here as this is already applied to our gRPC servers.

I see. Can we deprecate it and create `dapr-max-request-size` and use the old one as alias?

2023-05-16 02:43 UTC, yaron2 commented
> > > 1. Using `dapr-http-max-request-size` doesn't feel right for something that is related to gRPC. Should we have a separate CLI flag for this maybe? Also, whatever flag should also apply to our gRPC server too perhaps (not just for gRPC proxying).
> > 
> > 
> > We should reuse `dapr-http-max-request-size` here as this is already applied to our gRPC servers.
> 
> I see. Can we deprecate it and create `dapr-max-request-size` and use the old one as alias?

I don't see a reason to do that but we can consider a contribution (separate from this PR) in the future.

2023-05-16 19:37 UTC, Flern commented
@yaron2 - update pushed.  I also missed some significant infrastructure updates needed to allow the `dapr-http-max-request-size` to be included in service configurations for e2e deployments.  Having trouble running e2e locally, though, to verify that this will work.

2023-05-16 21:01 UTC, yaron2 requested changes

2023-05-16 21:01 UTC, yaron2 commented on tests/e2e/service_invocation/service_invocation_test.go
> +			MaxRequestSizeMB: 6,
You need to set `MaxRequestSizeMB` on `grpcproxyserver` as well. The YAML files under `tests/apps/` are not applied during the tests.

2023-05-16 22:44 UTC, yaron2 commented
@Flern you need to add gRPC options to the proxy server app [here](https://github.com/dapr/dapr/blob/master/tests/apps/service_invocation_grpc_proxy_server/app.go#L45) for `MaxRecvMsgSize` and `MaxSendMsgSize`.

2023-05-17 02:29 UTC, yaron2 approved these changes

2023-05-17 03:32 UTC, merged