[1.10] Fix bulk subscribe response
dapr/dapr pull request #6513
Opened 2023-06-14 15:44 UTC by DeepanshuA

# Description

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-06-16 04:17 UTC, mukundansundar requested changes
@DeepanshuA small nitpick changes in release notes.

2023-06-16 04:17 UTC, mukundansundar commented on docs/release_notes/v1.10.8.md
> +When App doesn't acknowledge properly Bulk Subscribe messages, with proper statuses json, then Bulk Subscribe was resulting in panic for components with Default Bulk Subscribe implementation.
```suggestion
When App doesn't acknowledge Bulk Subscribe messages with proper statuses json, then Bulk Subscribe was resulting in panic for components with Default Bulk Subscribe implementation.  
```

2023-06-16 04:17 UTC, mukundansundar commented on docs/release_notes/v1.10.8.md
> +The issue impacts users on Dapr 1.10.x who use Bulk Subscribe feature with a component having Default Bulk Subscribe implementation and their App not replying proper statuses json.
```suggestion
The issue impacts users on Dapr 1.10.x who use Bulk Subscribe feature with a component having Default Bulk Subscribe implementation and their App not replying with proper statuses json.
```

2023-06-21 00:48 UTC, artursouza approved these changes

2023-06-21 00:49 UTC, merged