Removing RpcException error for non-existent workflow in various commands
dapr/dapr pull request #6519
Opened 2023-06-14 22:02 UTC by RyanLettieri

# Description

## Issue reference

Please reference the issue this PR will close: [#_[issue number]_](https://github.com/dapr/dapr/issues/6432)

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-06-15 18:04 UTC, cgillum requested changes

2023-06-15 18:04 UTC, cgillum commented on pkg/runtime/wfengine/component.go
> +var ErrInstanceNotFound = errors.New("No such instance exists")
Shouldn't you be using backend.ErrInstanceNotFound instead of defining your own version here?

2023-06-15 18:04 UTC, cgillum commented on pkg/runtime/wfengine/component.go
> +		if err == ErrInstanceNotFound {
I think the correct way to compare errors in Go is to use `errors.Is(err, TheErrorImComparingTo)`

2023-06-15 18:04 UTC, cgillum commented on pkg/runtime/wfengine/component.go
> +			return nil, nil
What will be the HTTP status code that's returned in this case? I don't think it's appropriate for an HTTP API to return 200 in this case. Is there a way for us to return an HTTP 404 without returning an error?

2023-07-13 15:30 UTC, ItalyPaleAle reviewed
LGTM but with a couple of changes!

One note: this doesn't remove the "RpcException". The exception was thrown by the SDK so it's unrelated from this. This PR fixes the return status code for non-existing workflow :)

2023-07-13 15:30 UTC, ItalyPaleAle commented on pkg/messages/predefined.go
> +	ErrNoOrMissingWorkflowComponent  = APIError{"no workflow component was provided", "ERR_WORKFLOW_COMPONENT_MISSING", http.StatusNotFound, grpcCodes.NotFound}
Why was this changed to NotFound? I think BadRequest was better here

2023-07-13 20:24 UTC, cgillum approved these changes
LGTM!

2023-07-13 20:26 UTC, ItalyPaleAle commented on pkg/grpc/universalapi/api_workflow.go
>  	"github.com/dapr/components-contrib/workflows"
Please fix the linter issues

2023-07-13 20:28 UTC, yaron2 commented
@cgillum resolve conflicts please

2023-07-13 21:44 UTC, ItalyPaleAle approved these changes

2023-07-17 18:34 UTC, merged