Separate Actors reminders interface
dapr/dapr pull request #6633
Opened 2023-07-10 07:59 UTC by DeepanshuA

# Description

This is still a work in progress. Some UTs are still failing, I am fixing them.

## Issue reference

Please reference the issue this PR will close: #6591 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-07-11 00:05 UTC, yaron2 commented
@DeepanshuA what issue does this close?

2023-07-11 02:02 UTC, DeepanshuA commented
> @DeepanshuA what issue does this close?

hi @yaron2, this is to target https://github.com/dapr/dapr/issues/6591.

2023-07-11 05:43 UTC, artursouza commented
I am OK with this change as long as it does not bundle behavior changes and passes all our validations, including E2E tests, perf tests and SDK validation.

2023-07-11 05:53 UTC, yaron2 requested changes

2023-07-11 05:53 UTC, yaron2 commented on pkg/actors/config.go
> +// func (c *Config) GetRemindersPartitionCountForType(actorType string) int {
Remove commented code

2023-07-11 05:55 UTC, yaron2 commented on pkg/actors/core/actor_lock.go
> +package core
It's recommended to keep packages as flat as possible unless and only separate if needed. I feel that `core` is not descriptive enough of what the package means. If there's a better package name then lets change to that, if not, I'd rather move that under `actors`.

2023-07-14 19:08 UTC, DeepanshuA commented
Closing in lieu of https://github.com/dapr/dapr/pull/6669

2023-07-14 19:08 UTC, closed without merging