Added azure openai component.
dapr/dapr pull request #6678
Opened 2023-07-16 05:55 UTC by shivam-51

# Description

Add azure openai component to dapr. Refer to this PR for more details https://github.com/dapr/components-contrib/pull/2965

## Issue reference

https://github.com/dapr/components-contrib/issues/2716

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-07-16 05:56 UTC, shivam-51 commented
@ItalyPaleAle Please have a look.

2023-07-16 15:17 UTC, ItalyPaleAle commented on cmd/daprd/components/binding_azure_openai.go
> +//go:build allcomponents || stablecomponents
```suggestion
//go:build allcomponents
```

This component is not stable :)

2023-07-16 15:18 UTC, ItalyPaleAle requested changes
Thanks!

Please also run:

```
go get -u github.com/dapr/components-contrib@master
make modtidy-all
```

2023-07-17 15:25 UTC, ItalyPaleAle approved these changes

2023-07-19 13:35 UTC, ItalyPaleAle submitted a review, later dismissed

2023-07-19 13:56 UTC, ItalyPaleAle commented
@mukundansundar docs are here: https://github.com/dapr/docs/pull/3618

@shivam-51 looks like there's a failure building this, could you please take a look?

2023-07-19 14:08 UTC, mukundansundar commented
> @mukundansundar docs are here: [dapr/docs#3618](https://github.com/dapr/docs/pull/3618)
> 
> @shivam-51 looks like there's a failure building this, could you please take a look?

interesting that the label did not work and automatically create a docs issue ... will have a look at the workflow for it.

2023-07-21 16:52 UTC, shivam-51 commented
@ItalyPaleAle Please have a look. The linting should not fail now.

2023-07-24 16:07 UTC, merged