Flaky unit tests: fix many race conditions
dapr/dapr pull request #6775
Opened 2023-08-04 21:08 UTC by ItalyPaleAle

Also increases the timeout on resiliency tests which seem to sometimes take longer on our Actions runners

Should reduce flakiness in our unit tests.

> Every package should now pass tests with `go test -race` 🎉

2023-08-05 17:07 UTC, JoshVanL requested changes

2023-08-05 17:07 UTC, JoshVanL commented on pkg/actors/internal/config.go
> +	lock   sync.Mutex
Consider using a read write mutex

2023-08-05 17:29 UTC, ItalyPaleAle commented on pkg/actors/internal/config.go
> +	lock   sync.Mutex
Done

2023-08-05 19:14 UTC, JoshVanL approved these changes

2023-08-06 02:57 UTC, mukundansundar approved these changes

2023-08-06 04:34 UTC, merged