Fix wrong service invocation type in http tracing
dapr/dapr pull request #7088
Opened 2023-10-24 01:19 UTC by RayOnFire

# Description

If request contains header `dapr-app-id`, this PR will treat it as a service invocation.

## Issue reference

Please reference the issue this PR will close: #_[7085]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-10-24 01:31 UTC, ItalyPaleAle commented
Thanks for this!

I believe when #6919 is merged, it should supersede this issue and fix this bug too. Let's get that merged first :)

2023-10-24 01:32 UTC, ItalyPaleAle requested changes
Let’s wait on #6919 which should address this issue at the root.

2023-10-24 21:40 UTC, yaron2 commented
@RayOnFire if you can please pull the master branch version, build a `daprd` binary and see if the issue is now resolved, that would help a lot.

2023-11-07 00:35 UTC, daixiang0 commented on pkg/diagnostics/http_tracing.go
> +	appId := r.Header.Get("dapr-app-id")
```suggestion
	appID := r.Header.Get("dapr-app-id")
```

2023-11-07 00:38 UTC, ItalyPaleAle commented
In the current master branch, we changed how tracing works significantly. Could you please make sure this PR is still needed?

2023-11-16 17:14 UTC, yaron2 commented
Ping @RayOnFire

2024-01-15 17:51 UTC, yaron2 commented
Ping @RayOnFire

2024-01-16 02:05 UTC, RayOnFire commented
Hi, sorry for the late reply. I think in the current master branch, this PR is no longer needed. Thank you for your comment & code review!

2024-01-16 02:06 UTC, closed without merging