Fix Grafana dashboards.
dapr/dapr pull request #7121
Opened 2023-10-30 23:48 UTC by tmacam

The current grafana dashboards do not work in fresh cluster where
prometheus and grafana are installed using helm following Dapr Docs
(see [1], [2]). They refer to metrics that are not available in
such install.

Fixes #7120

[1]: https://docs.dapr.io/operations/observability/metrics/prometheus/#setup-prometheus-on-kubernetes
[2]: https://docs.dapr.io/operations/observability/metrics/grafana/#setup-on-kubernetes

Signed-off-by: Tiago Alves Macambira <tmacam@burocrata.org>

# Description

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-10-31 21:41 UTC, tmacam commented
Gathering all diffs from dapr/test-infra#204 we got to the following regex:

```
sed -i -e 's/\bkubernetes_name\b/service/g' -e 's/\bkubernetes_namespace\b/namespace/g' -e 's/\bkubernetes_node\b/node/g' -e 's/\bkubernetes_pod_name\b/pod/g' *.json
```

2023-11-02 06:01 UTC, mukundansundar requested changes
why is the grafana dashboard only limited to `longhaul_test`? And why are the service names hardcoded? 
Isn't this a general grafana dashboard that can be optionally installed on any dapr cluster?
cc @dapr/maintainers-dapr ?

2023-11-02 16:07 UTC, tmacam commented on grafana/grafana-actor-dashboard.json
> +          "value": "longhaul-test"
It doesn't have to be specific to longhauls, but if it is going to be a random string, why not have it be something useful?

2023-11-02 16:50 UTC, tmacam commented
@mukundansundar 

> why is the grafana dashboard only limited to `longhaul_test`?

It isn't. This PR accomplishes 2 things:

1. It fixes the names of the metrics being used so they refer to ones that exist on a default prometheus setup
2. sets defaults to so they work out-of-the-box with the longhaul-tests environments.

The last item is the contentious one so let me dive on it. While the last item might make you believe that we are limiting it to `longhaul-tests`, this isn't really the case.

First because grafana pics up the contents selectable for the variables `namespace` (which was a bad name, should prob be renamed as it collides with a metric name) and `dapr_app_id` from their associated queries. Upon loading this dashboard, the available options for these two variables will be collected by the available values set to the metrics they track. The user has only to manually select something for these two fields. That will be required **anyway**, both with the current code (unless applications are also run in a namespace called `pipeline` ) or after this PR  (unless applications are also run in a namespace called `longhaul-test`).

Second, you might observe that there already are hardcoded value for these 2 these variables: `namespace` is set to `pipeline` and `dapr_app_id` is set to `["loadtestclient", "stateactor"]`. So effectively we are just changing an arbitrary setting (that doesn't work out of the box and that doesn't refer to anything meaningful to the project) by another arbitrary setting so that it could work out of the box for the project.


>  And why are the service names hardcoded?

So that, upon install in a fresh longhaul cluster + grafana install, all apps existing are **selected** by default. I am just saving **us** a few clicks.

> Isn't this a general grafana dashboard that can be optionally installed on any dapr cluster?

My point is that it is just as generic as it was before. Upon loading, those variables whose values we are pre-feeding will be gathered by the metric queries associated with them.

2023-11-03 23:47 UTC, tmacam commented on grafana/grafana-actor-dashboard.json
> +          "value": "longhaul-test"
While I think it is safe to keep these longhaul settings for the reasons I mentioned before, I added a98f3f1b1f28b14af7827cc8e2f9f6551ea7c315 to remove those specific settings.

2023-11-04 05:25 UTC, mukundansundar approved these changes

2023-11-04 06:20 UTC, merged