[WIP] Deploy a Control Plane Service for Actors/Reminders
dapr/dapr pull request #7318
Opened 2023-12-19 17:27 UTC by DeepanshuA

# Description

This PR lets users configure their solution/ControlPlaneService for actors/reminders.
If nothing is given, traditional `placement` and inbuilt reminders will be used.

## Issue reference

Please reference the issue this PR links with: #7203 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2024-01-04 15:58 UTC, ItalyPaleAle commented
/test-version-skew

2024-01-15 05:53 UTC, yaron2 commented
@DeepanshuA see conflicts

2024-01-15 08:06 UTC, DeepanshuA commented
> @DeepanshuA see conflicts

Resolved

2024-01-15 18:56 UTC, JoshVanL requested changes

2024-01-15 18:56 UTC, JoshVanL commented on pkg/actors/providers.go
> +package actors
Please add copyright headers.

2024-01-15 18:56 UTC, JoshVanL commented on pkg/actors/providers_test.go
> +package actors
Headers.

2024-01-16 13:41 UTC, JoshVanL approved these changes

2024-01-16 14:16 UTC, mukundansundar commented
/test-version-skew

2024-01-16 14:17 UTC, mukundansundar commented
/ok-to-test

2024-01-16 14:17 UTC, mukundansundar commented
/ok-to-test

2024-01-16 15:15 UTC, mukundansundar commented
/test-version-skew

2024-01-16 15:19 UTC, mukundansundar approved these changes

2024-01-16 16:22 UTC, merged