Standardize crypto errors
dapr/dapr pull request #7558
Opened 2024-02-23 03:42 UTC by chaitanyab2311

# Description

Enriched errors in cryptography API. This is still a draft as unit tests need to be updated and integration tests need to be added

## Issue reference

Please reference the issue this PR will close: #7491 [https://github.com/dapr/dapr/issues/7491]_

## Checklist

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2024-02-23 03:43 UTC, chaitanyab2311 commented
@cicoyle I am getting some errors related to MockActors in http_test while running tests locally. Am i missing something

2024-02-23 04:14 UTC, ItalyPaleAle requested changes

2024-02-23 04:14 UTC, ItalyPaleAle commented on pkg/api/errors/cryptography.go
> +	message := "crypto providers not configured"
Please use consts for these things

2024-02-23 04:14 UTC, ItalyPaleAle commented on pkg/api/errors/cryptography.go
> +	message := fmt.Sprintf("failed to perform encrypt operation: %s", err.Error())
```suggestion
	message := "failed to perform encrypt operation: " + err.Error()
```

2024-02-23 04:14 UTC, ItalyPaleAle commented on pkg/api/errors/cryptography.go
> +	message := fmt.Sprintf("failed to perform decrypt operation: %s", err.Error())
```suggestion
	message := "failed to perform decrypt operation: " + err.Error()
```

2024-02-23 04:14 UTC, ItalyPaleAle commented on pkg/api/errors/cryptography.go
> +func CryptoProviderKeyOperation(name string, err string) error {
Err should be an error, also for consistency

2024-02-23 04:14 UTC, ItalyPaleAle commented on pkg/api/errors/cryptography.go
> +func CryptoProviderVerifySignatureOperation(name string, err string) error {
Ditto

2024-02-23 04:14 UTC, ItalyPaleAle commented on pkg/api/universal/subtlecrypto_subtlecrypto.go
> -		err = messages.ErrCryptoOperation.WithFormat("failed to wrap key")
Very important: please do not return the exact error returned by the component! That can be logged, but must not be returned to the user. The old code was overriding the error for a reason.

See the comment above. The exact error must **never** be sent to users, or really bad things (side channel attacks) could happen

2024-02-23 04:16 UTC, ItalyPaleAle commented
Please note that with crypto operations, errors are sensitive as they can disclose information to users that can be used for attacks (side channel).

Please make sure errors from the crypto components are never returned to callers. They are ok to log, but not returned in the API response - return a generic "failed to perform operation" error instead.

2024-02-23 14:30 UTC, cicoyle commented
> @cicoyle I am getting some errors related to MockActors in http_test while running tests locally. Am i missing something

I believe you might need the tags in your Go Tool Args. When you run the tests in Dapr you will likely need to add these tags: `-tags=stablecomponents,unit`
![image](https://github.com/dapr/dapr/assets/25733780/2da51167-9196-41d7-bf09-7598f486ecb6)

Once you get to the integration tests too, you will need a tag: `go test -v -race -tags integration ./tests/integration -focus errors`, where `errors` might change pending what you'd like to 'focus' on

2024-02-23 14:32 UTC, cicoyle commented on pkg/api/errors/cryptography.go
> +func CryptoNotFound(name string) error {
same here. There is a generic `NotFound` you can use here: https://github.com/dapr/dapr/blob/master/pkg/api/errors/errors.go#L11

2024-02-23 14:40 UTC, cicoyle commented on pkg/api/errors/cryptography.go
> +func CryptoProviderGetKey(name string, err string) error {
```suggestion
func CryptoProviderGetKey(name string, msg string) error {
```
Then you can get rid of the `message := err` line below :)

Or if the intent was to use the string version of the initial error, then it should be of type `error` when passed in

2024-02-23 22:46 UTC, chaitanyab2311 commented on pkg/api/errors/cryptography.go
> +	message := "crypto providers not configured"
Added

2024-02-23 22:46 UTC, chaitanyab2311 commented on pkg/api/universal/subtlecrypto_subtlecrypto.go
> -		err = messages.ErrCryptoOperation.WithFormat("failed to wrap key")
Thanks for this. I should have read the comments properly. Modified the changes accordingly

2024-02-23 23:43 UTC, ItalyPaleAle commented on pkg/api/universal/subtlecrypto_subtlecrypto.go
> +		err = apierrors.CryptoProviderEncryptOperation(in.ComponentName, err)
Nit: use [`errors.New`](https://pkg.go.dev/errors#New) if there's no format (like, no `%s`), which is faster (same below)

```suggestion
		err = apierrors.CryptoProviderEncryptOperation(in.ComponentName, errors.New("failed to encrypt"))
```

2024-02-23 23:43 UTC, ItalyPaleAle commented on pkg/api/universal/subtlecrypto_subtlecrypto.go
> +		err = apierrors.CryptoProviderDecryptOperation(in.ComponentName, err)
```suggestion
		err = apierrors.CryptoProviderDecryptOperation(in.ComponentName, errors.New("failed to decrypt"))
```

2024-02-23 23:43 UTC, ItalyPaleAle commented on pkg/api/universal/subtlecrypto_subtlecrypto.go
> +		err = apierrors.CryptoProviderKeyOperation(in.ComponentName, err)
```suggestion
		err = apierrors.CryptoProviderKeyOperation(in.ComponentName, errors.New("failed to wrap key"))
```

2024-02-23 23:43 UTC, ItalyPaleAle commented on pkg/api/universal/subtlecrypto_subtlecrypto.go
> +		err = apierrors.CryptoProviderKeyOperation(in.ComponentName, err)
```suggestion
		err = apierrors.CryptoProviderKeyOperation(in.ComponentName, errors.New("failed to unwrap key"))
```

2024-02-23 23:43 UTC, ItalyPaleAle commented on pkg/api/universal/subtlecrypto_subtlecrypto.go
> +		err = apierrors.CryptoProviderKeyOperation(in.ComponentName, err)
```suggestion
		err = apierrors.CryptoProviderKeyOperation(in.ComponentName, errors.New("failed to sign"))
```

2024-02-23 23:43 UTC, ItalyPaleAle commented on pkg/api/universal/subtlecrypto_subtlecrypto.go
> +		err = apierrors.CryptoProviderVerifySignatureOperation(in.ComponentName, err)
```suggestion
		err = apierrors.CryptoProviderVerifySignatureOperation(in.ComponentName, errors.New("failed to verify signature"))
```

2024-02-23 23:43 UTC, ItalyPaleAle commented on pkg/api/errors/cryptography.go
Just a nit, I'd name this "crypto.go" since that's how all other files are named

2024-05-01 17:06 UTC, yaron2 commented
@chaitanyab2311 are you planning to take this PR out of draft?

2024-05-13 00:59 UTC, daixiang0 commented
ping @chaitanyab2311

2024-07-19 01:19 UTC, closed without merging