ci: add 'mikeee' to dapr-bot owners
dapr/dapr pull request #7592
Opened 2024-03-05 21:40 UTC by mikeee

# Description

Request to add myself to owners for the dapr-bot

## Issue reference

Please reference the issue this PR will close: #N/A

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2024-03-05 22:01 UTC, JoshVanL requested changes
I approve!

small nit from me.

2024-03-05 22:01 UTC, JoshVanL commented on .github/scripts/dapr_bot.js
> +    'mikeee'
Please put names in alphabetical (I know yours isn’t the first to be out of sort!)

2024-03-05 22:24 UTC, JoshVanL approved these changes

2024-03-06 05:57 UTC, cicoyle approved these changes

2024-03-06 06:15 UTC, yaron2 approved these changes

2024-03-06 06:15 UTC, merged