Up grpc version
dapr/dapr pull request #7806
Opened 2024-06-11 17:29 UTC by cicoyle

When updating the grpc version, I noticed the test failing due to the return value changing

There is a note in the [v1.62.0 dependencies section](https://github.com/grpc/grpc-go/releases/tag/v1.62.0) about:
![image](https://github.com/dapr/dapr/assets/25733780/c9d4e31e-0eae-4f17-9e54-2b753929ebd3)

Therefore, I've updated the unit test accordingly since:
- previously, when a nil message was passed to the Marshal function, it resulted in an error.
This means if the gRPC server method returned nil, nil, it would cause the server to return an error due to the marshaling failure. 
- now, when a nil message is passed to the Marshal function, it outputs zero bytes without an error.
As a result, if the gRPC server method returns nil, nil, the server now returns an empty message without an error.

2024-06-11 17:33 UTC, JoshVanL approved these changes

2024-06-11 18:05 UTC, cicoyle commented
last commit was to fix this panic: https://github.com/dapr/dapr/actions/runs/9470168103/job/26090820065?pr=7806

2024-06-12 09:31 UTC, mikeee requested changes
Should we go to 1.64.0 (we would need to change the way we initialize connections)

2024-06-12 09:31 UTC, mikeee commented on go.mod
> +	google.golang.org/grpc v1.62.1
The upgraded version is still vulnerable to a recently fixed DOS exploit.
https://github.com/grpc/grpc-go/releases/tag/v1.62.2

2024-06-12 13:35 UTC, cicoyle commented on go.mod
> +	google.golang.org/grpc v1.62.1
I see. I'll change it to 1.62.2 then, but don't want to address the deprecations with upgrading to 1.64 quite yet. This PR was just to address a unit test failure with the Scheduler branch in isolation.

2024-06-12 15:48 UTC, mikeee approved these changes
lgtm

2024-06-14 01:04 UTC, artursouza approved these changes

2024-06-14 01:04 UTC, merged

2024-06-17 14:32 UTC, marcduiker commented
@holopin-bot @cicoyle Enjoy your Dapr badge!