WIP: Fix Unit Test General Flakiness
dapr/dapr pull request #7818
Opened 2024-06-17 22:22 UTC by cicoyle

Working to fix the flakiness in unit tests in CI. They pass locally, so need to test a few things in CI since the behavior is different.

2024-06-18 13:50 UTC, cicoyle commented
Looks like the last unit test failure is due to the membership test, [which is fixed here](https://github.com/dapr/dapr/pull/7817)

2024-06-18 14:46 UTC, JoshVanL requested changes

2024-06-18 14:46 UTC, JoshVanL commented on pkg/operator/api/informer/informer_test.go
> +		}, 5*time.Second, 100*time.Millisecond)
We want to print out the values if it does fail. This also has a data race so we need to change `i.batchID` to be a `atomic.Uint32.

```suggestion
		require.EventuallyWithT(t, func(c *assert.CollectT) {
			assert.Equal(t, 1, i.batchID)
		}, 5*time.Second, 100*time.Millisecond)
```

2024-06-18 14:46 UTC, JoshVanL commented on pkg/operator/api/informer/informer_test.go
> +			return i.batchID == 2
Same here.

2024-06-18 14:46 UTC, JoshVanL commented on pkg/operator/api/informer/informer_test.go
> +			return i.batchID == 3
Same here.

2024-06-18 18:05 UTC, cicoyle commented
it looks like the memory utilization actually decreased, but idk why the go routines upped by 1 for this diff:
`75th percentile for number of go routines (new): 37.00`

2024-06-18 19:00 UTC, cicoyle commented on pkg/diagnostics/resiliency_monitoring_test.go
> +				time.Sleep(1000 * time.Millisecond)
I think its just a timing issue for this: https://github.com/dapr/dapr/actions/runs/9570009389/job/26384075690?pr=7818

2024-06-19 15:26 UTC, JoshVanL approved these changes

2024-06-19 17:36 UTC, merged