Revert "Change default cardinality to low for metrics (#7522)"
dapr/dapr pull request #7826
Opened 2024-06-19 23:03 UTC by artursouza

# Description

This reverts commit c3baea50a19e8e00793f5d79929edce45fc4c5e2.

Proposal to postpone decision to make low cardinality default, done in https://github.com/dapr/dapr/pull/7522

## Issue reference

Please reference the issue this PR will close: N/A

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2024-06-19 23:11 UTC, artursouza commented on charts/dapr/crds/configuration.yaml
> +                          but will be changed to false in 1.14+'
I can update this message too, just waiting for this run to finish.

2024-06-19 23:12 UTC, ItalyPaleAle requested changes

2024-06-19 23:12 UTC, ItalyPaleAle commented on charts/dapr/crds/configuration.yaml
> +                          but will be changed to false in 1.14+'
You may need to update this

2024-06-19 23:12 UTC, ItalyPaleAle commented on pkg/apis/configuration/v1alpha1/types.go
> +	// TODO @ItalyPaleAle [MetricsCardinality] Change default in 1.14
Update this

2024-06-19 23:17 UTC, yaron2 commented
Context:

After testing the low cardinality mode as default for a while and having received a satisfactory amount of user feedback, it becomes clear that while this enabling or disabling by default cannot be summarized into a right/wrong decision and both carry pros and cons that will better optimize for a certain class of users. The overall feedback received is that users want the ability to easily turn off high cardinality metrics if they need to, and a subset of users would very much benefit more granular control over the metrics configuration, such as path matching and regex, to allow power users to tailor metrics to their needs. With the implications of making metrics less usable out of the box for new users and potentially disrupting dashboards, monitoring and observability platform ingesting Dapr metrics of existing users, it would be preferable to follow how way sister projects like Istio and Linkerd handle the situation, which is to keep high cardinality as default and provide users with the best experience of opting out or arriving at a desired custom configuration.

2024-06-20 13:56 UTC, cicoyle approved these changes
Changes look fine, but there are some failing int tests that I believe should be passing before this gets merged

2024-06-20 23:53 UTC, artursouza commented
> Changes look fine, but there are some failing int tests that I believe should be passing before this gets merged

I think I fixed now. Let's see.

2024-06-21 15:31 UTC, yaron2 approved these changes

2024-06-21 15:31 UTC, merged