bugfix workflowstate encoding, missing generation field
dapr/dapr pull request #7892
Opened 2024-07-04 14:33 UTC by famarting

# Description

This PR updates the functions `EncodeWorkflowState` and `DecodeWorkflowState` so they dont use an embedded struct definition and instead use a well defined struct, additionally this PR adds the field `Generation` to the encoded data and a test to verify encoding and decoding works as expected.

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2024-07-04 14:34 UTC, JoshVanL requested changes

2024-07-04 14:34 UTC, JoshVanL commented on pkg/runtime/wfengine/backends/actors/workflowstate_test.go
> +package actors
Add copyright header

2024-07-05 21:42 UTC, ItalyPaleAle submitted a review, later dismissed

2024-07-05 21:50 UTC, yaron2 commented
Linter @famarting

2024-07-12 10:19 UTC, famarting commented
tests need retrigger, these failures seem unrelated to my changes

2024-07-12 15:28 UTC, yaron2 approved these changes

2024-08-08 14:03 UTC, elena-kolevska approved these changes

2024-09-03 14:58 UTC, famarting commented
ping, we need this 😄

2024-09-03 16:09 UTC, merged