fix(helm): add annotations key to allow for annotations
dapr/dapr pull request #7921
Opened 2024-07-19 19:24 UTC by sicoyle

# Description

backport of https://github.com/dapr/dapr/pull/7920

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2024-07-19 19:59 UTC, cicoyle submitted a review, later dismissed

2024-07-19 20:08 UTC, ItalyPaleAle requested changes

2024-07-19 20:08 UTC, ItalyPaleAle commented on charts/dapr/charts/dapr_operator/templates/dapr_operator_service.yaml
> +  {{ toYaml .Values.apiService.annotations | indent 4}}
You must add `-` at the start or the first line will have indentation of 6 (and the second of 4)
```suggestion
  {{- toYaml .Values.apiService.annotations | indent 4}}
```

2024-07-19 20:08 UTC, ItalyPaleAle commented on charts/dapr/charts/dapr_placement/templates/dapr_placement_service.yaml
> +  {{ toYaml .Values.service.annotations | indent 4}}
Same

```suggestion
  {{- toYaml .Values.service.annotations | indent 4}}
```

2024-07-19 20:08 UTC, ItalyPaleAle commented on charts/dapr/charts/dapr_sentry/templates/dapr_sentry_service.yaml
> +  {{ toYaml .Values.service.annotations | indent 4}}
```suggestion
  {{- toYaml .Values.service.annotations | indent 4}}
```

2024-07-19 20:08 UTC, ItalyPaleAle commented on charts/dapr/charts/dapr_sidecar_injector/templates/dapr_sidecar_injector_service.yaml
> +  {{ toYaml .Values.service.annotations | indent 4}}
```suggestion
  {{- toYaml .Values.service.annotations | indent 4}}
```

2024-08-26 15:20 UTC, cicoyle commented
I've adding @ItalyPaleAle's suggestions. lgtm

2024-10-03 13:19 UTC, JoshVanL approved these changes

2024-12-09 13:43 UTC, closed without merging