Release notes for 1.14.5
dapr/dapr pull request #8126
Opened 2024-09-19 20:19 UTC by antontroshin

2024-09-19 20:23 UTC, JoshVanL requested changes

2024-09-19 20:23 UTC, JoshVanL commented on docs/release_notes/v1.14.5.md
> +Cloudevents data was being sent as plain text and Cloudevents Middleware was not able to parse the data resulting in 415 error code.
```suggestion
Outbox transactions were not respecting metadata. 
Cloudevents Middleware was unable to parse the metadata, resulting in 415 error codes.
```

2024-09-19 20:23 UTC, JoshVanL commented on docs/release_notes/v1.14.5.md
> +- [Fix content type metadata from query for outbox transaction](#fix-content-type-metadata-from-query-for-outbox-transaction)
```suggestion
- [Fix content type metadata from query for outbox transactions](#fix-content-type-metadata-from-query-for-outbox-transaction)
```

2024-09-19 20:23 UTC, JoshVanL commented on docs/release_notes/v1.14.5.md
> +## Fix content type metadata from query for outbox transaction
```suggestion
## Fix content type metadata from query for outbox transactions
```

2024-09-19 20:23 UTC, JoshVanL commented on docs/release_notes/v1.14.5.md
> +Transactions were not respecting the metadata in the transaction request.
```suggestion
Outbox transactions were not respecting the metadata in the transaction request.
```

2024-09-24 17:39 UTC, antontroshin commented on docs/release_notes/v1.14.5.md
> +- [Fix content type metadata from query for outbox transaction](#fix-content-type-metadata-from-query-for-outbox-transaction)
Done

2024-09-24 17:39 UTC, antontroshin commented on docs/release_notes/v1.14.5.md
> +## Fix content type metadata from query for outbox transaction
Done

2024-09-24 17:39 UTC, antontroshin commented on docs/release_notes/v1.14.5.md
> +Transactions were not respecting the metadata in the transaction request.
Done

2024-09-24 17:39 UTC, antontroshin commented on docs/release_notes/v1.14.5.md
> +Cloudevents data was being sent as plain text and Cloudevents Middleware was not able to parse the data resulting in 415 error code.
Done

2024-09-26 19:42 UTC, JoshVanL approved these changes

2024-09-26 19:42 UTC, merged