Adds integration tests for metrics in the placement service
dapr/dapr pull request #8218
Opened 2024-10-21 22:01 UTC by elena-kolevska

# Description

Adding integration tests before the Open Census to the Open Telemetry change, so we can confirm that no regressions have been introduced.

## Issue reference

https://github.com/dapr/dapr/issues/7225

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [X] Code compiles correctly
- [X] Created/updated tests
- [ ] Unit tests passing
- [ ] End-to-end tests passing
- [ ] Extended the documentation / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Specification has been updated / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Provided sample for the feature / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_

2024-10-23 23:03 UTC, JoshVanL requested changes
Big fan 😄

2024-10-23 23:03 UTC, JoshVanL commented on tests/integration/framework/process/metrics/metrics.go
> +func (m *Metrics) MatchMetric(args ...string) []Metric {
```suggestion
func (m *Metrics) MatchMetric(substrings ...string) []Metric {
```

2024-10-23 23:03 UTC, JoshVanL commented on tests/integration/framework/process/metrics/metrics_test.go
> +package metrics
Nit: copyright

2024-10-24 09:34 UTC, elena-kolevska commented on tests/integration/framework/process/metrics/metrics.go
> +			if !strings.Contains(key, arg) {
```suggestion
		// Check if all substrings are present in the key
		for _, substring := range substrings {
			if !strings.Contains(key, substring) {
```

2024-12-02 17:52 UTC, JoshVanL submitted a review, later dismissed

2024-12-17 21:49 UTC, yaron2 approved these changes

2024-12-17 22:12 UTC, JoshVanL approved these changes

2024-12-18 18:18 UTC, artursouza approved these changes

2024-12-18 18:18 UTC, merged