Verify Scheduler Enabled
dapr/dapr pull request #8238
Opened 2024-10-24 20:29 UTC by cicoyle

Verify Scheduler is enabled before connecting.

2024-10-24 20:53 UTC, artursouza approved these changes

2024-10-25 00:39 UTC, JoshVanL requested changes

2024-10-25 00:39 UTC, JoshVanL commented on pkg/runtime/runtime.go
> +			log.Errorf("Scheduler enabled, but dapr failed to connect. Unable to use the Jobs API.")
This error must be returned.

2024-10-25 00:39 UTC, JoshVanL commented on pkg/runtime/runtime.go
> +	if runtimeConfig.SchedulerEnabled() {
Both of these runners are designed to be able to run, regardless of whether there are any addresses/clients. Scheduler is also signaled as enabled if there is a non zero number of addresses. It's not clear to me why we need this change at all.

2025-03-08 04:02 UTC, closed without merging