Add Workflow Stable proto API
dapr/dapr pull request #8253
Opened 2024-10-30 07:21 UTC by antontroshin

# Description

Add Workflow Stable proto API
Add deprecation notice on Workflow Alpha1 API

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] Code compiles correctly
- [ ] Created/updated tests
- [ ] Unit tests passing
- [ ] End-to-end tests passing
- [ ] Extended the documentation / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Specification has been updated / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Provided sample for the feature / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_

2024-10-30 11:42 UTC, elena-kolevska requested changes
You'll also need to add the methods in `pkg/api/universal/workflow.go`, update the endpoints and ideally, update e2e tests. You can refer to [this PR](https://github.com/dapr/dapr/pull/6911) for guidance on things that are needed when upgrading an API.

2024-10-30 18:16 UTC, antontroshin commented
> You'll also need to add the methods in `pkg/api/universal/workflow.go`, update the endpoints and ideally, update e2e tests. You can refer to [this PR](https://github.com/dapr/dapr/pull/6911) for guidance, I think it will be helpful.

It is indeed very helpful, thanks a lot!

2024-11-11 01:12 UTC, elena-kolevska commented
Heya @antontroshin  pls ping when this is ready for review 🙏

2024-11-14 23:27 UTC, antontroshin commented
@elena-kolevska Sorry missed the comment, this is ready for review. TY.

2024-11-18 12:30 UTC, mikeee reviewed
Will these endpoints be retained solely used for HTTP invocations - as the dapr workflow grpc endpoints are being retired

E.g.  https://github.com/dapr/go-sdk/pull/640

2024-11-19 00:12 UTC, elena-kolevska approved these changes
LGTM, but @mikeee's question is a good one. If we're deprecating the "main client" workflows in all sdks, will we need to add the stable endpoints?

2024-11-20 20:19 UTC, mikeee requested changes

2024-11-20 20:19 UTC, mikeee commented on dapr/proto/runtime/v1/dapr.proto
> +
As mentioned yesterday I think these methods should be removed

2024-11-20 21:53 UTC, antontroshin commented
Closing. Workflow APIs are being deprecated (https://github.com/dapr/dapr/pull/8299) and the Workflow client will be used instead.

2024-11-20 21:53 UTC, closed without merging