WIP: Fix/placement dissemination hang
dapr/dapr pull request #8326
Opened 2024-12-02 15:01 UTC by elena-kolevska

## Issue reference

https://github.com/dapr/dapr/issues/7031

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] Code compiles correctly
- [ ] Created/updated tests
- [ ] Unit tests passing
- [ ] End-to-end tests passing
- [ ] Extended the documentation / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Specification has been updated / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Provided sample for the feature / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_

2025-01-15 00:11 UTC, antontroshin commented on pkg/placement/placement.go
> +		log.Infof("Stream connection for app %s is disconnected with the error: %v.", hostName, err)
Should this be `log.Errorf`? It would be easier to spot in logs and logging apps like Kibana, Loki, etc., when filtering by level.

2025-01-15 12:20 UTC, elena-kolevska commented on pkg/placement/placement.go
> +	}
I updated the code so it fails with a proper error. 
It can't be retried because it's a user error in startup arguments.

2025-01-15 12:21 UTC, elena-kolevska commented on pkg/placement/monitoring/metrics.go
> +
I had done this last week, per Alice's suggestion, but hadn't pushed. Thanks for catching it.

2025-01-15 12:49 UTC, JoshVanL commented on pkg/placement/placement.go
> +	}
Please don’t panic in the middle of runtime.

If the error is not recoverable, we should error exit the process. If we _really_ have to exit the process (?)

2025-01-15 14:02 UTC, JoshVanL requested changes

2025-01-15 14:02 UTC, JoshVanL commented on pkg/placement/leadership.go
> +			log.Error("attempted to start the leader loop while running", p.raftNode.GetID())
Why don't we catch this error?

2025-01-15 14:02 UTC, JoshVanL commented on pkg/placement/leadership.go
> +				log.Error("placement leader loop failed", "error", err)
Same here

2025-01-15 14:02 UTC, JoshVanL commented on pkg/placement/leadership.go
> +		}
Why would this ever happen?

2025-01-15 14:02 UTC, JoshVanL commented on pkg/placement/membership.go
> +		sendCtx, sendCancelFn := context.WithTimeout(ctx, 2*time.Second) // We should make this configurable
This isn't a very long time, why 2 seconds?

2025-01-15 18:20 UTC, elena-kolevska commented on pkg/placement/membership.go
> +		sendCtx, sendCancelFn := context.WithTimeout(ctx, 2*time.Second) // We should make this configurable
Yes, I wanted to discuss this value. I believe it should be configurable because it's a function of the underlying network as well as the number of dissemination messages we're expecting and how quickly can the sidecars process them; it can't be too long because it would imply we're locking all daprds for a long time (during dissemination). What would you suggest as a good default?

2025-01-15 19:48 UTC, elena-kolevska commented on pkg/placement/leadership.go
> +				log.Error("placement leader loop failed", "error", err)
Logically, we should be able to ignore this error. We would only get it if `p.raftNode.Raft(ctx)` returns an error, which only happens if the underlying raft server is not ready in time. But we would have never gotten the isLeader signal in the first palce if the raft server wasn't ready.

2025-01-20 17:06 UTC, JoshVanL approved these changes

2025-02-04 16:49 UTC, JoshVanL commented
@elena-kolevska tests failing

2025-02-04 17:51 UTC, elena-kolevska commented
> @elena-kolevska tests failing

Yeah, that's cause I reverted the error code fixes and put them in a separate PR. All the placement tests have been passing consistently for a few runs though. I just merged latest release, let's see if they pass.

2025-02-06 00:09 UTC, JoshVanL approved these changes

2025-02-06 00:09 UTC, merged