Error Code Metrics Improved Testing+Recording
dapr/dapr pull request #8345
Opened 2024-12-11 16:42 UTC by jake-engelberg

# Description

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] Code compiles correctly
- [ ] Created/updated tests
- [ ] Unit tests passing
- [ ] End-to-end tests passing
- [ ] Extended the documentation / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Specification has been updated / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Provided sample for the feature / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_

2024-12-11 23:14 UTC, elena-kolevska requested changes

2024-12-11 23:14 UTC, elena-kolevska commented on tests/integration/framework/process/daprd/daprd.go
> +func (d *Daprd) Metrics(t *testing.T, ctx context.Context, desiredNameAndLabelPairs ...string) map[string]float64 {
@jake-engelberg  Take a look at this PR, seems to be relevant here. https://github.com/dapr/dapr/pull/8218
@JoshVanL can we merge that please to unblock this PR?

2024-12-13 02:26 UTC, jake-engelberg commented on pkg/api/grpc/grpc.go
>  			err = status.Errorf(codes.Internal, messages.ErrStateGet, in.GetKey(), in.GetStoreName(), err.Error())
I've done essentially this, lmk if it's what you envisioned.

2024-12-13 11:52 UTC, elena-kolevska commented on pkg/api/grpc/grpc.go
> +			return status.Errorf(codes.InvalidArgument, format, args...), codes.InvalidArgument
Wouldn't it be simpler if we updated this method to return the Basic() error instead?

2024-12-20 13:15 UTC, elena-kolevska commented
Hey @jake-engelberg , ping me when I can re-review. I'll hold on updating the error codes in docs until this gets merged.

2025-01-07 23:16 UTC, elena-kolevska requested changes

2025-01-07 23:16 UTC, elena-kolevska commented on tests/integration/framework/process/metrics/metrics.go
> +	for _, metric := range metrics {
The sum here is not completely intuitive, from the name, but the function is simple enough to understand, so we can leave it.

2025-01-14 19:36 UTC, jake-engelberg commented on pkg/api/grpc/grpc.go
> -		err = a.stateErrorResponse(err, messages.ErrStateSave, in.GetStoreName(), err.Error())
This was replaced with `apierrors.Basic()`.
`apierrors.Basic` from my understanding is returning a kit error:
<img width="406" alt="Screenshot 2025-01-14 at 2 35 24 PM" src="https://github.com/user-attachments/assets/0ca2421f-3a92-4284-8518-e5b19eb4d495" />
https://github.com/jake-engelberg/dapr//blob/b5d4747b009477c6f7a8194b9a734b810c7ea28c/pkg/api/errors/errors.go#L26-L36

2025-01-14 19:39 UTC, jake-engelberg commented on pkg/diagnostics/errorcode_monitoring.go
> +func RecordErrorCodeEarly(err error) bool {
Yeah, I only did a wrapper to differentiate it from the desired usage of `RecordErrorCode()`, but I'll just put a comment at the point of usage instead.

2025-01-14 19:44 UTC, jake-engelberg commented on pkg/api/grpc/grpc_test.go
> +		richError := apierrors.Basic(a.getStateErrorCode(err), http.StatusInternalServerError, errorcodes.StateSave, fmt.Sprintf(messages.ErrStateSave, "a", err.Error()))
Could you specify what you think should be changed further?

I'm aware the test originally just looked at the single function and not with `apierrors.Basic()`, but it seems to just wrap the result further, so it is a more comprehensive check.

2025-01-15 23:26 UTC, elena-kolevska commented on pkg/api/grpc/grpc.go
> -		err = a.stateErrorResponse(err, messages.ErrStateSave, in.GetStoreName(), err.Error())
Yes, we'd still return a kit error, but we'll lose any specific information that has been set on that error.

2025-01-15 23:33 UTC, elena-kolevska commented on pkg/api/grpc/grpc_test.go
> +		richError := apierrors.Basic(a.getStateErrorCode(err), http.StatusInternalServerError, errorcodes.StateSave, fmt.Sprintf(messages.ErrStateSave, "a", err.Error()))
I was just saying that since we changed the nature of the `stateErrorResponse` function (it only returns a code now) we should change the test too, so it only compares the code. No need to build full error objects.

2025-01-16 20:32 UTC, jake-engelberg commented on pkg/api/grpc/grpc.go
> -		err = a.stateErrorResponse(err, messages.ErrStateSave, in.GetStoreName(), err.Error())
While the format is changing, my undestanding is the original error is kept and stringified as the kiterror message:
<img width="1354" alt="Screenshot 2025-01-16 at 3 32 03 PM" src="https://github.com/user-attachments/assets/2ef1105b-26e5-4fc5-b44f-5e02da148125" />

2025-01-21 23:46 UTC, elena-kolevska submitted a review, later dismissed
Great work on adding additional metrics check in the integration tests!

2025-01-22 19:02 UTC, yaron2 approved these changes

2025-01-24 22:03 UTC, merged